### ISSUE TITLE
Question: What is the relationships with DataKernel?

### ISSUE THREAD

**Issue by sirinath** [activej/activej#1]
This project looks very much like DataKernel. What is the relationship between these projects?

Should I use ActiveJ or DataKernel in a project?

**Comment by necauqua** [comment]
ActiveJ is a rebranding of the DataKernel project, it's just the same codebase, but the project and everything related (package names, docs etc) renamed to ActiveJ.
Also it uses the semantic versioning system now.

From now on, the DataKernel will be discontinued, and you may use ActiveJ instead.

**Comment by sirinath** [comment]
Can this information be put on the DataKernel website and readme so users can find their way here? It is by chance that I found this project. If not I will still be using DataKernel,

**Comment by necauqua** [comment]
Fair point, we will do just that, thanks

**Comment by sirinath** [comment]
Have you got a Twitter handler for the new project so I can follow announcements and even perhaps send some quick comments?
