### ISSUE TITLE
Request Parameters Mapping | JAX-RS and Spring Rest Parity with Annotation Based Configuration

### ISSUE THREAD

**Issue by sirinath** [activej/activej#10]
Can you give an example in the documentation on how request parameters are handled:
- Cookie parameters
- Header parameters
- Path parameters
- Query parameters
- Form parameters
- Matrix parameters
- etc.

I am looking to see how this mapping is made using annotation.

**Comment by sirinath** [comment]
Can annotation-based configuration be brought to parity with JAX-RS and Spring Rest.

**Comment by eduard-vasinskyi** [comment]
Hello, @sirinath 
ActiveJ is designed to be an 'explicit' framework, while annotation-based configuration is more of an implicit approach. We believe that is much more easier/reliable to write applications that are explicitly configured.

As for handling HTTP parameters, you can refer to [HTTP examples](https://activej.io/http.html) or you can check public API of [HttpRequest](https://github.com/activej/activej/blob/master/core-http/src/main/java/io/activej/http/HttpRequest.java)
