### ISSUE TITLE
Is any way can hot reload?

### ISSUE THREAD

**Issue by loveu8** [activej/activej#106]
Hello there,
I make a simple code to play, but I test this. It can't hot reload my project. Is any way or example can do this?
Thank you do this cool thing :D

**Comment by eduard-vasinskyi** [comment]
Hi, @loveu8

Hot reload is out of the scope of the ActiveJ framework. There are third-party tools that you may use to enable hot reload support (HotSwap, DCEVM, etc) for ActiveJ. However, we recommend you just to build a project upon new changes.

**Comment by loveu8** [comment]
@eduard-vasinskyi thank your reply :D. I will test what you recommed pulgin.
