### ISSUE TITLE
CORS Setting

### ISSUE THREAD

**Issue by mercury-bluefox** [activej/activej#109]
Hello, i have successully test my simple activej application in local. When i try to deploy it on google cloud run, browser test is running fine. I got an CORS issue accessing my app from other server.
How to allow cors setting in activej ?

Thank you

**Comment by loveu8** [comment]
Cors setting you can set your reponse header "Access-Control-Allow-Origin".
`HttpResponse.ok200().withHeader(HttpHeaders.ACCESS_CONTROL_ALLOW_ORIGIN, "*");`

**Comment by mercury-bluefox** [comment]
Thank you. Can you please suggest me, where can i found complete documentation of this lib ?

**Comment by loveu8** [comment]
I just check the source code to find it. The document is not complete all detail. sometime you have using key word find this repo.

**Comment by mercury-bluefox** [comment]
Thank you

**Comment by laran** [comment]
How would cors be applied for a react app? The examples show using a StaticServlet to serve a react app at "/". StaticServlet doesn't seem to support headers, making it unclear to me how to return the required header for cors.

**Comment by eduard-vasinskyi** [comment]
Hi, @laran

[StaticServlet](https://github.com/activej/activej/blob/master/core-http/src/main/java/io/activej/http/StaticServlet.java) is an instance of [AsyncServlet](https://github.com/activej/activej/blob/master/core-http/src/main/java/io/activej/http/AsyncServlet.java) which is basically a function that transforms an [HttpRequest](https://github.com/activej/activej/blob/master/core-http/src/main/java/io/activej/http/HttpRequest.java) into a Promise of [HttpResponse](https://github.com/activej/activej/blob/master/core-http/src/main/java/io/activej/http/HttpResponse.java). You can wrap any `AsyncServlet` into a new `AsyncServlet` that transforms a resulting response by adding the required headers. 

For CORS you can wrap a `StaticServlet` into something like this:

```java
private static AsyncServlet withCORS(AsyncServlet servlet){
  return request -> servlet.serveAsync(request)
        .map(response -> response.withHeader(ACCESS_CONTROL_ALLOW_ORIGIN, "*"));
}
```
 
The above solution is applicable to any `AsyncServlet`. A more specific solution for `StaticServlet` would be to supply a predefined `HttpResponse` by using a `StaticServlet#withResponse` method. 

You can modify a `@Provides` method for `StaticServlet` to something like this:

```java
@Provides
AsyncServlet servlet(Executor executor) {
  return StaticServlet.ofClassPath(executor, "build")
        .withResponse(() -> HttpResponse.ok200()
              .withHeader(ACCESS_CONTROL_ALLOW_ORIGIN, "*"))
        .withIndexHtml();
}
```
