### ISSUE TITLE
Support Web Services

### ISSUE THREAD

**Issue by sirinath** [activej/activej#11]
Can web services supported with parity in functionality with JAX-WS, Spring, Axis2, CXF, etc. with annotation based configuration.

A possible list of technologies to support:
- SOAP
- WSDL
- MTOM
- XML-RPC
- JSON
- JSON-RPC
- XML
- XML-RPC
- OData
- REST
- Binary protocols:
  - SBE
  - MsgPacket
  - etc.
- IPC framework
- P2P framework
- IoT framework
  - MQTT
  - etc.
- Browser communication
  - WebSocket
  - Server-Sent Events
  - WebRTC
  - etc.
- etc.

**Comment by eduard-vasinskyi** [comment]
Hello, @sirinath 
ActiveJ is designed in a way to be orthogonal to other frameworks/protocols. You can use existing frameworks or protocol implementations alongside ActiveJ.
For example, you can use any JSON parsing library to decode messages received via HTTP. ActiveJ does not limit your choice here. So, it is up to developer to decide what tools/protocols to use and ActiveJ will serve as a foundation for your application.

Another example is [Template Engine Integration](https://activej.io/tutorials/template-engine-integration.html) It shows how you can combine ActiveJ with [mustache](https://github.com/spullara/mustache.java) templating engine, which is not part of ActiveJ. If you, by some chance, prefer different templating engine, you can easily switch.

**Comment by sirinath** [comment]
Excuse me for the elementary questions. 

How do I have something like this:

```java
import javax.jws.WebMethod;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Endpoint;

@WebService
@SOAPBinding(style = SOAPBinding.Style.DOCUMENT)
public class TestService {

	@WebMethod
	public String sayHello(String msg){
		return "Hello "+msg;
	}
	
	public static void main(String[] args){
		Endpoint.publish("https://localhost:8888/testWS", new TestService());
	}
}
```

**Comment by eduard-vasinskyi** [comment]
Hello, @sirinath 
ActiveJ does not have a built-in parser for XML nor does it depend on third-party parsing libraries. It is up to you as a programmer to choose XML parser that suits your likings and/or business needs. 
For example, you can use Java's SAAJ API to work directly with SOAP messages. Or you can choose any other library for XML processing
In this case, ActiveJ can be used as an HTTP client/server.

**Comment by sirinath** [comment]
@eduard-vasinskyi Many thanks for the time and effort to answer my questions.

Also, I am feeling guilty for asking so many questions on the issue tracker. Maybe we can enable GitHub discussions and/or have a forum. Discourse has a free forum for Open Source project: https://blog.discourse.org/2018/11/free-hosting-for-open-source-v2/
