### ISSUE TITLE
[serializer] Multidimensional array's don't work

### ISSUE THREAD

**Issue by alphaqu** [activej/activej#114]
The title is self-explanitory.

Running: 5.0-beta1

**Comment by eduard-vasinskyi** [comment]
Hi, @alphaqu
We have improved a [SerializerBuilder ](https://github.com/activej/activej/blob/master/core-serializer/src/main/java/io/activej/serializer/SerializerBuilder.java)to support type use annotations. This has allowed us to get rid of serializer annotations with the `path` attribute, as those were a bit counter-intuitive to use. Now you can annotate types directly, as in `List<@SerializeNullable String>` to serialize a list of nullable strings. 

Array annotations may seem a little tricky at first, but it is fully [JLS](https://docs.oracle.com/javase/specs/jls/se8/html/jls-9.html#jls-9.7.4) compatible.

You can look at the [example](https://activej.io/serializer/examples#path-based-serialization) that demonstrates how you can use new annotations. You can also refer to the [‘serializer’ module tests](https://github.com/activej/activej/tree/master/core-serializer/src/test/java/io/activej/serializer) as there are examples of array serialization using both path-based annotation and type-use annotations.

Unfortunately, older versions of Java do not properly implement type use annotations. As a result, some complex type use annotations may not work for older versions of Java. If some annotations seem to not work for you, try to upgrade to Java 9+. If you cannot upgrade, you can still use old path-based annotations but you would need to enable `SerializerBuilder#withAnnotationCompatibilityMode`

We have added [tests](https://github.com/activej/activej/blob/master/core-serializer/src/test/java/io/activej/serializer/SerializerBuilder2Test.java) that demonstrate that multidimensional arrays actually work when run on Java 9.

**Comment by eduard-vasinskyi** [comment]
Since tests for multidimensional arrays do not fail and there were no new mentions of such problems, I'll close the issue. Feel free to reopen this if the issue still persists.
