### ISSUE TITLE
[Promise] null handle and cast operators (suggestions)

### ISSUE THREAD

**Issue by Qudratillo** [activej/activej#119]
@eduard-vasinskyi Thank you for making ActiveJ more fun to work with

I suggest to introduce new map and then functions when result is null (or not null)
Here I share my Kotlin code and I think it explains my suggestion well
```
fun <T> Promise<T?>.thenWhenNull(fn: Supplier<Promise<T>>): Promise<T> = thenCatching {
    if (it == null) fn.get() else Promise.of(it)
}

fun <T, R> Promise<T?>.thenWhenNotNull(fn: Function<T, Promise<R>>): Promise<R> = thenCatching {
    if (it != null) fn.apply(it) else Promise.of(null)
}

fun <T, R> Promise<T?>.mapWhenNull(fn: Supplier<T>): Promise<T> = mapCatching {
    it ?: fn.get()
}

fun <T, R> Promise<T?>.mapWhenNotNull(fn: Function<T, R>): Promise<R> = mapCatching {
    if (it != null) fn.apply(it) else null
}
```

And one more method to cast
```
fun <T : R, R> Promise<T>.cast(): Promise<R> = mapCatching { it }
```

**Comment by eduard-vasinskyi** [comment]
Hi, @Qudratillo

Thank you for your suggestions.

We have implemented null handling methods as well as a cast() method. You can check them out in the ‘master’ branch. These changes will be a part of a final v5.0 release.

**Comment by Qudratillo** [comment]
@eduard-vasinskyi Thank you
