### ISSUE TITLE
Inject: Kotlin support for sets and map

### ISSUE THREAD

**Issue by richarddd** [activej/activej#123]
Hi,

Currently we have to explicity specify `java.util.Set` and `java.util.Map` for kotlin bindings when using `@ProvidesIntoSet` or `bindIntoSet`

It would be great if we could support Kotlin Sets and Maps or at least this limitation is documented:

**Works:**
```kotlin
class Test @Inject constructor(val set: java.util.Set<Hej>)
```
**Breaks:**
```kotlin
class Test @Inject constructor(val set: Set<Hej>)
```

**Comment by eduard-vasinskyi** [comment]
Hi, @richarddd

I have tried to reproduce an issue locally, but everything seems to be working fine without specifying `java.util.` package. You can take a look at the example [here](https://github.com/eduard-vasinskyi/activej-kotlin-di-demo). It uses both Java and Kotlin modules with [@ProvidesIntoSet](https://github.com/activej/activej/blob/master/core-inject/src/main/java/io/activej/inject/annotation/ProvidesIntoSet.java) annotations.

Could you please share a reproducible snippet or an example project that demonstrates the problem?

**Comment by richarddd** [comment]
@eduard-vasinskyi I've managed to reproduce the issue. Check out my fork of your demo and see the failing tests:
https://github.com/richarddd/activej-kotlin-di-demo

**Comment by eduard-vasinskyi** [comment]
@richarddd 
Feel free to reopen this if the issue still persists.
