### ISSUE TITLE
What are the risks if eventloop.withCurrentThread() is called in other threads

### ISSUE THREAD

**Issue by zhangtianxiao** [activej/activej#128]

**Comment by eduard-vasinskyi** [comment]
Hi, @zhangtianxiao 

`withCurrentEventloop()` method is used to register an Eventloop into an inner ThreadLocal. The registration also happens automatically when you call `Eventloop#run` but sometimes you need to execute Eventloop-related code prior to calling `Eventloop#run`. This is useful for tests, for example, when you need to initialize a component in a context of an Eventloop but prior to `Eventloop#run` invocation. Do not call this method after `Evenloop#run` has been called.
