### ISSUE TITLE
Which async database driver is used with activeJ

### ISSUE THREAD

**Issue by zhangtianxiao** [activej/activej#131]
to replace blocking JDBC,

**Comment by eduard-vasinskyi** [comment]
Hi, @zhangtianxiao

ActiveJ does not use any external drivers for databases. Instead it allows you to choose any driver you wish. Blocking JDBC calls should be handled by an external Executor. For convenience, we provided `Promise.ofBlocking()` methods. 

You can find examples of how to use ActiveJ for JDBC calls [here](https://github.com/activej/activej/tree/master/examples/core/sql). There are also [examples](https://github.com/activej/activej/blob/master/examples/core/sql/src/main/java/advanced/JooqSqlLauncher.java) of how to use ActiveJ with popular ORM frameworks (JOOQ).

Also, take a look at ActiveJ high-performance [Redis client](https://github.com/activej/activej/tree/master/extra/cloud-redis) ([examples](https://github.com/activej/activej/tree/master/examples/cloud/redis/src/main/java))- it is a native Redis client implementation which is designed to be fully compatible with ActiveJ high-performance threading and asynchronous I/O model.
