### ISSUE TITLE
 Can Project Loom help activej optimize callbacks?

### ISSUE THREAD

**Issue by zhangtianxiao** [activej/activej#132]
coding in flatten rather than nest

**Comment by eduard-vasinskyi** [comment]
Hi, @zhangtianxiao

Our closure-based Promise implementation has an optimal threading model with ultimate performance capabilities. However, we look forward to the release of Project Loom as it will make blocking calls easier and not rely on heavy threads. 

We will consider integration of ActiveJ with Project Loom once it is released and  proven to be a production-ready technology.
