### ISSUE TITLE
multipart request - mapping to POJO - Direct APIs

### ISSUE THREAD

**Issue by kkr2606** [activej/activej#134]
I am trying to make CRUD application with ActiveJ as backend, Svelte as frontend and Neo4j as database. I have only two fields in my POJO. One of them is List. I don't know how to parse the multipart POST request coming from my front end application made in svelte to my POJO instance. Then subsequently I can save in DB. It's the foundation requirement for my project.

It's my POJO class.

![image](https://user-images.githubusercontent.com/63806026/143777736-2ae0b7c8-7d5a-4bc8-908b-2a93590cfd5e.png)

It's my POST request handler;

![post-req](https://user-images.githubusercontent.com/63806026/143777807-bafd1e61-9d12-4cd7-9380-5bc2f53aa0d3.png)

It's my form made in svelte:

![image](https://user-images.githubusercontent.com/63806026/143777964-778f45de-7b8e-4b4b-9fcf-a81e08e279c3.png)

**Comment by eduard-vasinskyi** [comment]
Hi, @kkr2606

I assume that a body of the request looks something like this:
```
name: “some name”
values: “[value1, value2, value3, ...]”
```
And post parameters are encoded as _multipart/form-data_.

You can parse all the parameters to a map (using `HttpRequest#handleMultipart` method) and then use this map to construct an `Enumeration` instance. You will need to use some JSON parsing library (e.g. Gson, Jackson, etc.) to decode “values” string parameter to a List of Strings.

Here is how your code may look like:
```java
.map(POST, "/api/enum/create", request -> {
  Map<String, String> fields = new HashMap<>();
  return request.handleMultipart(fieldsToMap(fields))
        .then(() -> {
           String nameParam = fields.get("name");
           String valuesParam = fields.get("values");
 
           // Use any JSON library to parse ‘values’ JSON to a List<String>
           List<String> values = parseJson(valuesParam);
 
           Enumeration enumeration = new Enumeration(nameParam, values);
 
           return saveToDb(enumeration)
                 .map($ -> HttpResponse.ok200());
        });
});
```
Notice that `saveToDb(Enumeration)` method returns a [Promise](https://activej.io/async-io/promise). If saving to DB requires some I/O operations you should execute it asynchronously in an external `Executor` as to not block the current eventloop thread.

However, _multipart/form-data_ encoding is usually used for file uploads. It is more natural to post simple parameters using _application/x-www-form-urlencoded_ encoding. I believe you can update the Svelte code to change the POST encoding. If you do so, you can skip the `handleMultipart()` step and obtain POST parameters directly from the `HttpRequest`.
Your code would look something like this:
```java
.map(POST, "/api/enum/create", request -> request.loadBody()
     .then(() -> {
        String nameParam = request.getPostParameter("name");
        String valuesParam = request.getPostParameter("values");
 
        // Use any JSON library to parse values JSON to a List<String>
        List<String> values = parseJson(valuesParam);
 
        Enumeration enumeration = new Enumeration(nameParam, values);
 
        return saveToDb(enumeration)
              .map($ -> HttpResponse.ok200());
     }));
```
Notice that you need to loadBody() first before accessing POST parameters.

Or as another alternative, you could have encoded the whole request body as a JSON and then decode an Enumeration instance directly.

PS. We have added a simple “Hello World” [example](https://github.com/activej/activej/tree/examples-5.1/examples/tutorials/svelte-integration) of ActiveJ + Svelte integration.

**Comment by kkr2606** [comment]
Thanks for the awesome explanation! and commit of **Svelte - ActiveJ** integration example in the repo. Both Svelte and ActiveJ surpasses its own competitors in terms of performance. Reason, we picked them.
