### ISSUE TITLE
Getting-Started tutorial should move away from 5.0-SNAPSHOT version ? 

### ISSUE THREAD

**Issue by tarunjoshi-lily** [activej/activej#136]
I just tried ActiveJ tutorial, from the documentation it looks promising. But from the tutorial https://activej.io/tutorials/getting-started , maven wasn't able to import the snapshot jar from pom.xml . I updated it by looking it up the latest version from search.maven.org. May be the documentation is required to be updated?

**Comment by eduard-vasinskyi** [comment]
Hi, @tarunjoshi-lily

Thank you for spotting that!

We have reworked and simplified some of our tutorials to have an explanation of a source code from a pre-cloned tutorial project. You can look at the updated tutorial [here](https://activej.io/tutorials/getting-started)

Please, let us know if you have any questions regarding ActiveJ documentation or examples. We will be glad to help!

**Comment by tarunjoshi-lily** [comment]
Thank you eduard for responding ! I have lot of questions , I am surfing around the tutorials. But given the huge scope (Event loop, RPC, fastest serializer ) that this web server has to offer, is there a better way to ask some questions like Gitter/Slack/developer community emails ?

**Comment by eduard-vasinskyi** [comment]
@tarunjoshi-lily  you can contact us at contact@activej.io

**Comment by eduard-vasinskyi** [comment]
@tarunjoshi-lily You can also ask questions in [GitHub Discussions](https://github.com/activej/activej/discussions)
