### ISSUE TITLE
Question: Multi Threaded Routing Module Servelet 

### ISSUE THREAD

**Issue by sirinath** [activej/activej#14]
How do you create a multi-threaded routing module servelet so all available CPU cores are utilised?

Also in the routing module servelet how do you make a distinction on what type of request is made when the `method` is not provided? Within this context how can parameters be accessed?

**Comment by sirinath** [comment]
Simple test code I am using:

```java
import io.activej.http.AsyncServlet;
import io.activej.http.HttpResponse;
import io.activej.http.RoutingServlet;
import io.activej.http.inject.RouterModule;
import io.activej.http.inject.RouterModule.Router;
import io.activej.http.inject.RouterModule.Mapped;
import io.activej.inject.Injector;
import io.activej.launcher.Launcher;
import io.activej.inject.annotation.Provides;
import io.activej.launchers.http.MultithreadedHttpServerLauncher;
import io.activej.worker.annotation.Worker;
import io.activej.inject.module.Module;
import io.activej.inject.module.Modules;
import io.activej.worker.annotation.WorkerId;

public final class ApplicationLauncher extends MultithreadedHttpServerLauncher {
    @Override
    protected Module getBusinessLogicModule() {
        return Modules.combine(new RouterModule());
    }

    @Provides
    AsyncServlet servlet(@Router AsyncServlet router) {
        return router;
    }

    @Provides
    @Worker
    @Mapped("/")
    AsyncServlet main(@WorkerId int workerId) {
        return request -> HttpResponse.ok200().withPlainText("hello world: " + workerId);
    }

    public static void main(String[] args) throws Exception {
        Injector.useSpecializer();

        Launcher launcher = new ApplicationLauncher();
        launcher.launch(args);
    }
}
```

I get 404 Not Found error.

**Comment by sirinath** [comment]
@eduard-vasinskyi Any way a multi-threaded and rounding module servlets can be combined, i.e., creating a multi-threaded routing module servelet?

**Comment by eduard-vasinskyi** [comment]
Hello, @sirinath 
Yes, you can use routing servlet in multithreaded context.
The preffered way is to specify all of the mappings directly. 
If you wish, you can omit HTTP method while configuring routes in `RoutingServlet`. You can determine a method of HTTP request based on result of `request.getMethod()` call. But it is more convenient to specify the method to be handled. Mappings that do not specify HTTP method are primarly useful for providing fallback servlets, or for combining with other routing servlets that have mappings for multiple methods.

Here is a snippet that demonstrates how to do that:
```java
package io.activej.launchers.http;

import io.activej.http.AsyncServlet;
import io.activej.http.HttpResponse;
import io.activej.http.RoutingServlet;
import io.activej.inject.Injector;
import io.activej.inject.annotation.Named;
import io.activej.inject.annotation.Provides;
import io.activej.worker.annotation.Worker;
import io.activej.worker.annotation.WorkerId;

import static io.activej.http.HttpMethod.GET;
import static io.activej.http.HttpMethod.POST;

public final class ApplicationLauncher extends MultithreadedHttpServerLauncher {

	@Provides
	@Worker
	AsyncServlet servlet(@WorkerId int workerId, @Named("API") AsyncServlet apiServlet) {
		return RoutingServlet.create()
				.map(GET, "/", request -> HttpResponse.ok200()
						.withPlainText("hello world: " + workerId))
				.map("/allMethods", request -> HttpResponse.ok200()
						.withPlainText("Called with HTTP method: " + request.getMethod()))
				.map("/api/*", apiServlet);
	}

	@Provides
	@Worker
	@Named("API")
	AsyncServlet apiServlet(@WorkerId int workerId) {
		return RoutingServlet.create()
				.map(GET, "/resource", request -> HttpResponse.ok200()
						.withPlainText("Getting a resource from worker: " + workerId))
				.map(POST, "/resource", request -> HttpResponse.ok200()
						.withPlainText("Posting a resource to worker: " + workerId));
	}

	public static void main(String[] args) throws Exception {
		Injector.useSpecializer();

		new ApplicationLauncher().launch(args);
	}
}
```
Note how HTTP method of the request is accessed in `/allMethods` mapping.
An API servlet that has mappings for different methods is mapped to `/api/*` endpoint that does not specify HTTP method. As a result, requests are correctly passed to the API servlet to be handled.

To learn more about servlets and how parameters are handled, please refer to examples:
[Multithreaded server](https://activej.io/http.html#multithreaded-server-example)
[Request parameters](https://activej.io/http.html#request-parameters-example)
[Routing servlet](https://activej.io/http.html#routing-servlet-example)

**Comment by sirinath** [comment]
Can I used `@Mapped("/xyz")` for convenience in the above context? If so how?

**Comment by eduard-vasinskyi** [comment]
Hello, @sirinath 
`RouterModule` is supported only for single-threaded servers. You have to map servlets to corresponding paths by hand, similarly to example from this [reply](https://github.com/activej/activej/issues/14#issuecomment-654704933)

>    // Also at this point if I want to read a cookie how do I do it?

You can read a cookie directly from a request by calling either 
`@Nullable String getCookie(String)` - to read a single cookie
or
`Map<String,String> getCookies()` - to retrieve all of the cookies from a request

You can refer to API of [HttpRequest](https://github.com/activej/activej/blob/master/core-http/src/main/java/io/activej/http/HttpRequest.java) if you need help with accessing cookies or other request parameters. Or you can look at examples on the website that I have provided in previous reply.

> Also, what does this piece of code do in the example on your site

`Modules.combine()` allows you to combine bindings from different modules as if it is a single module. If your application has several modules, you could use `Modules.combine()` to return a single module from `getBusinessLogicModule()` method or `getOverrideModule()`.

> Also how does getBusinessLogicModule() compare with getOverrideModule()?

If you specify a duplicate binding in `getBusinessLogicModule()` you will catch an exception, as bindings with same keys are forbidden. 
However, if you want to override existing bindings with your own, you can use `getOverrideModule()` for this. For example, you can override default Config provided in `HttpServerLauncher` by overriding `getOverrideModule()` and returning a module that contains binding for a new Config.

You can refer to [documentation](https://inject.activej.io/docs.html) for more information. Or you can look at API/javadocs of [Injector](https://github.com/activej/activej/blob/master/core-inject/src/main/java/io/activej/inject/Injector.java), [Launcher](https://github.com/activej/activej/blob/master/launcher/src/main/java/io/activej/launcher/Launcher.java) or [HttpServerLauncher](https://github.com/activej/activej/blob/master/launchers/http/src/main/java/io/activej/launchers/http/HttpServerLauncher.java)
