### ISSUE TITLE
Side Bar is not Scroll-able 

### ISSUE THREAD

**Issue by sirinath** [activej/activej#2]
In the documentation section, the sidebar is not scrollable. So it is not possible to see what is under `Misc`:

![image](https://user-images.githubusercontent.com/637415/85204397-d2d27a00-b331-11ea-8d84-c281974aee7c.png)

**Comment by sirinath** [comment]
@necauqua can this issue be fixed soon so that the full documentation is browsable as this does not require much effort since the documentation is already there?

**Comment by necauqua** [comment]
@valerialistratova is responsible for documentation and site layout and they will fix that as soon as possible

**Comment by valerialistratova** [comment]
@sirinath the issue was fixed
