### ISSUE TITLE
Support for SameSite Cookies

### ISSUE THREAD

**Issue by a1730** [activej/activej#203]
We have a site that currently fails with Google Chrome clients and it turns out to be due to our SameSite setting that was accidentally set to "Laxi".  Direct support for SameSite from ActiveJ with enums would have prevented this problem at compile time.

We are reluctant to use setExtension because we do not fully understand its purpose within the framework. The HttpCookie  class is final.

Do you have plans to directly support SameSite cookies? SameSite is part of [draft-ietf-httpbis-rfc6265bis-09](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-rfc6265bis-09) which is due to expire on April 22, 2022, so it is understandable if you do not want to support it. However, ActiveJ currently has direct support for other header keys in section 5.4 of the proposal.

Thank you for ActiveJ.

**Comment by eduard-vasinskyi** [comment]
Hi, @a1730
We have added built-in support for **SameSite** cookies. Now you can use `HttpCookie#withSameSite` or `HttpCookie#setSameSite` to add a corresponding **SameSite** enum value to the cookie. 
These changes can be found in [this branch](https://github.com/activej/activej/tree/master-5.2), they will be part of the ActiveJ v5.2 release.

**Comment by a1730** [comment]
Wow! That was fast!! Thank you!!!
