### ISSUE TITLE
Documentation issue: Tutorials > Template engine integration

### ISSUE THREAD

**Issue by valbaca** [activej/activej#212]
I came across ActiveJ after finding it topping the charts for most performant Java framework [web-frameworks-benchmark.netlify.app](https://web-frameworks-benchmark.netlify.app/result?asc=0&l=java&metric=totalRequestsPerS&order_by=level512)

As I was going through the documentation, I noticed a pretty confusing section. Under the [Template engine integration](https://activej.io/tutorials/template-engine-integration) the `AsyncServlet` code is missing. Instead, the `ApplicationLauncher` code is repeated again.

Ctrl-f for "Next, we provide AsyncServlet:"

<img width="1552" alt="Screen Shot 2022-06-27 at 7 16 57 PM" src="https://user-images.githubusercontent.com/318337/176077108-0b98bd51-4c5b-4434-8ca7-b4e949f59763.png">

**Comment by eduard-vasinskyi** [comment]
Hi, @valbaca.

Thanks for noticing this! We've updated the snippet for the AsyncServlet provider method.

If you find any other inconsistencies on the website or maybe you have questions about ActiveJ, feel free to ask them here or in the [Discussions](https://github.com/activej/activej/discussions) tab.
