### ISSUE TITLE
[Documentation] Additional Routing Examples 

### ISSUE THREAD

**Issue by sirinath** [activej/activej#23]
Can you provide examples on:
- routing based on MIME types
- virtual hosts
- forwarding support
- multiple routes and ordering
- context data
- reroute
- localised response
- etc.

**Comment by eduard-vasinskyi** [comment]
Hello, @sirinath 
I have provided some examples in issue #21

**Comment by eduard-vasinskyi** [comment]
We have added some examples of dynamic request routing:
- [Routing based on host](https://github.com/activej/activej/blob/master/examples/core/http/src/main/java/HostRoutingExample.java)
- [Routing based on MIME type](https://github.com/activej/activej/blob/master/examples/core/http/src/main/java/MimeTypeRoutingExample.java)
- [Routing based on Cookie](https://github.com/activej/activej/blob/master/examples/core/http/src/main/java/CookieRoutingExample.java)
- [Randomized routing](https://github.com/activej/activej/blob/master/examples/core/http/src/main/java/DynamicRoutingExample.java)
