### ISSUE TITLE
ClientHelloInfo in handles

### ISSUE THREAD

**Issue by ja3abuser** [activej/activej#237]
Hello! I need TLS ClientHelloInfo in route handlers, can it be made with ActiveJ?

**Comment by eduard-vasinskyi** [comment]
Hi, @wireguard-dev

If I understand correctly, ClientHelloInfo is Go’s approach for supporting Server Name Indication (SNI). Right now, ActiveJ does not support SNI. We advise to use ActiveJ with a reverse-proxy that supports SNI (like Nginx, etc.).
