### ISSUE TITLE
Release Notes

### ISSUE THREAD

**Issue by sirinath** [activej/activej#25]
Is it possible to publish a release note with new versions on what changed and what is new?

**Comment by valerialistratova** [comment]
Hello, @sirinath, thanks for the suggestion. We've added a Blog section to cover release updates and remarkable platform features. You can already find a quick overview of v2.0 release [here](https://activej.io/blog/release-notes-v2.html).

**Comment by sirinath** [comment]
This is great. But now there is no link to https://activej.org/ on https://activej.io/.

**Comment by valerialistratova** [comment]
We've decided to  locate all the ActiveJ content on https://activej.io, for better convenience
