### ISSUE TITLE
Http 307/308

### ISSUE THREAD

**Issue by a1730** [activej/activej#26]
Please add HTTP 307/308 support to the HTTP server.  ActiveJ http will move closer to [rfc7231](https://tools.ietf.org/html/rfc7231#section-6.4.7) and  [rfc7538](https://tools.ietf.org/html/rfc7538#section-3) respectively. We found the required changes to be so minimal that is not worth a fork.

Thank you.

**Comment by eduard-vasinskyi** [comment]
Hello, @a1730 
Thanks for a suggestion!
We will be adding support for HTTP 307/308 responses in ActiveJ version 2.1 alongside with web socket support.
So stay tuned for announcements about new releases.

**Comment by eduard-vasinskyi** [comment]
@a1730 
A support for 307/308 HTTP responses has already been pushed to master branch.
These changes will be released in ActiveJ version 2.1.

**Comment by a1730** [comment]
Awesome. Thanks!
