### ISSUE TITLE
activej-Inject, How to omit `getInstanceInjector(...).injectInto(...)`

### ISSUE THREAD

**Issue by zhangtianxiao** [activej/activej#269]
code like this.

```java
class Test {
  @Inject
  String name;
}

class MyBeansDescription {

  @Provides
  public static String name() {
    return "Alice";
  }

  @Provides
  public static Test test() {
    return new Test();
  }

  public static void main(String[] args) {
    ModuleBuilder mb = ModuleBuilder.create()
      .scan(MyBeansDescription.class)
      .bindInstanceInjector(Test.class);
      //.bind(Test.class);

    Injector injector = Injector.of(mb.build());
    Test test = injector.getInstance(Test.class);

    // null
    System.out.println(test.name);
    // ? How to omit this step
    injector.getInstanceInjector(Test.class).injectInto(test);
    // Alice
    System.out.println(test.name);
  }
}
```
Thanks!

**Comment by zhangtianxiao** [comment]
I try other way.
```java
@Inject
class Test {
  @Inject
  String name;
}

class MyBeansDescription {

  @Provides
  public static String name() {
    return "Alice";
  }
//  @Provides
//  public static Test test() {
//    return new Test();
//  }

  public static void main(String[] args) {
    ModuleBuilder mb = ModuleBuilder.create()
      .scan(MyBeansDescription.class)
      .bind(Test.class);

    Injector injector = Injector.of(mb.build());
    Test test = injector.getInstance(Test.class);

    // Alice
    System.out.println(test.name);
    // Alice
    System.out.println(test.name);
  }
}
```
It works fine. Bug I still want to provide ` @ Provider`

**Comment by eduard-vasinskyi** [comment]
Hi, @zhangtianxiao

Instance injectors are not called automatically by the `Injector` as it is the user's job to create instances (inject them with dependencies). Plus, calling instance injectors manually allows for a more controlled instance lifecycle.

As for your second question: placing `@Inject` annotation on a class or its constructor generates a binding for that class. So, it is equivalent to adding `@Provides` annotated method to the module.

If you want to add the `@Provides`-method, you can omit the `@Inject` annotation on the `Test` class. You also would need to add the constructor to the `Test` class that sets `String name`:
```java
class Test {
  String name;


  public Test(String name){
     this.name = name;
  }
}


class MyBeansDescription {


  @Provides
  public static String name() {
     return "Alice";
  }


  @Provides
  public static Test test(String name) {
     return new Test(name);
  }
}
```

**Comment by zhangtianxiao** [comment]
> Hi, @zhangtianxiao
> 
> Instance injectors are not called automatically by the `Injector` as it is the user's job to create instances (inject them with dependencies). Plus, calling instance injectors manually allows for a more controlled instance lifecycle.
> 
> As for your second question: placing `@Inject` annotation on a class or its constructor generates a binding for that class. So, it is equivalent to adding `@Provides` annotated method to the module.
> 
> If you want to add the `@Provides`-method, you can omit the `@Inject` annotation on the `Test` class. You also would need to add the constructor to the `Test` class that sets `String name`:
> 
> ```java
> class Test {
>   String name;
> 
> 
>   public Test(String name){
>      this.name = name;
>   }
> }
> 
> 
> class MyBeansDescription {
> 
> 
>   @Provides
>   public static String name() {
>      return "Alice";
>   }
> 
> 
>   @Provides
>   public static Test test(String name) {
>      return new Test(name);
>   }
> }
> ```

Problem was resolved.
My real purpose is to provide a custom bean creator to the injector.
thanks for your reply.
```java
mb.bind(Test.class)
      .to(Test_Enhanced::new);
```
