### ISSUE TITLE
ActiveJ Serializer - Non-static POJOs?

### ISSUE THREAD

**Issue by akumaburn** [activej/activej#274]
I noticed that all the examples are using **static** inner classes when serializing / de-serializing a POJO ; since most, if not all my POJOs aren't static inner classes..

1. Is it even possible to use the ActiveJ Serializer in this case?
2. How? Can you provide me a simple example with a basic non-static class POJO?

**Comment by akumaburn** [comment]
@eduard-vasinskyi

Thank you! 

Though that is a rather complicated example for a simple Serialize/De-Serialize with top level POJOs

I had previously tried to serialize top-level POJOs using the other examples (with the inner static classes) on the website as a guide (https://activej.io/serializer/examples) to no-success as the non-static classes couldn't be found at runtime. Usage was adapted to:

`
BinarySerializer<LocalDateHolder> serializer = SerializerBuilder.create().with(LocalDate.class, ctx -> new SerializerDefLocalDate()).build(LocalDateHolder.class);
`

and 

`BinarySerializer<Person> serializer = SerializerBuilder.create().build(Person.class);`

Both styles of which failed at runtime.

I had noticed that in your example, the process to create the SerializerBuilder usage is different from the static examples (in that you get the ClassLoader from the current thread rather than passing in the class itself and you appear to pass subclasses to it afterwards?), perhaps it would be worthwhile to add this usage to the documentation on: https://activej.io/serializer/examples

If there is additional documentation on the **SerializerBuilder** class that I'm not aware of, let me know.

```
private ClassLoader classLoader = Thread.currentThread().getContextClassLoader();
private SerializerBuilder serializerBuilder = SerializerBuilder.create(DefiningClassLoader.create(classLoader));
private BinarySerializer<RpcMessage> serializer = serializerBuilder.withSubclasses(RpcMessage.MESSAGE_TYPES, messageTypes).build(RpcMessage.class);
```

**Comment by eduard-vasinskyi** [comment]
@akumaburn
Could you share a demo project or a unit test that demonstrates that serialization fails for top-level POJOs? I’ll be glad to help you with that.

**Comment by akumaburn** [comment]
@eduard-vasinskyi   I've added the examples here: https://github.com/akumaburn/ActiveJExample

For a normal execution scenario, example2 is failing, not sure why..

For a maven goal **exec:java** all of them are failing. I suspect there's something extra that needs to be added to maven for it to work with exec plugin?

This project was built with intellij and I've included the idea files if it helps to load it.

**Comment by eduard-vasinskyi** [comment]
@akumaburn 

The problem with _example2_ is that you have added a `surname` field, but you never set it before serialization. The field is `null`, so the serializer fails with `NullPointerException`.

To fix this, you either need to set `surname` field to a non-null value or you can mark `surname` field as nullable via `@SerializeNullable` annotation:
```java
@Serialize
@SerializeNullable
public String getSurname() {
   return surname;
}
```

As for the exec plugin, it seems to be a known [issue](https://github.com/mojohaus/exec-maven-plugin/issues/327). Everything seems to work fine when using the `java` tool to execute your code. 

A workaround is to pass a thread’s context classloader to `SerializerBuilder`:
```java
ClassLoader contextClassLoader = Thread.currentThread().getContextClassLoader();
DefiningClassLoader definingClassLoader = DefiningClassLoader.create(contextClassLoader);
SerializerBuilder serializerBuilder = SerializerBuilder.create(definingClassLoader);
```
