### ISSUE TITLE
HTTP server Middleware

### ISSUE THREAD

**Issue by Arkady-Dymkov** [activej/activej#275]
Hi! First, thank you for you work!
I didn't find any documentation about middleware. Mostly i'm interested in exception handler and response wrapper.

1. I want to add custom exception handling with additional logic
2. I want to wrap every response to my custom response type

If there is a way how to make it, please, share!

**Comment by eduard-vasinskyi** [comment]
Hi, @Arkady-Dymkov 

You can find documentation/examples about HTTP module [here](https://activej.io/http). There are also examples for using `RoutingServlet`. 

To wrap a response into a custom response you can create an `AsyncServlet` which wraps another `AsyncServlet` and then customize the response. You can add a custom exception handler the same way:
```java
AsyncServlet mainServlet = createMainServlet();
AsyncServlet exceptionHandlingServlet = request ->
     mainServlet.serveAsync(request)
           .map((httpResponse, e) -> {
              if (e != null) {
                 // do something with exception or return a different response


                 return HttpResponse.ofCode(400).withPlainText("Bad request");
              }


              return httpResponse;
           });
```

**Comment by ints-hiro** [comment]
1. You can see example about error handler at my repo: https://github.com/anboo44/activej-real-world-example/blob/master/src/main/java/com/uet/example/api/ServletCenter.java
2. Wrap response to custom type: 
+ Define common method: https://github.com/anboo44/activej-real-world-example/blob/feature/test-hibernate/src/main/java/com/uet/example/api/controller/BaseController.java
+ Use it at controller: ```
    public Promise<HttpResponse> list(HttpRequest request) {
        return userRepository.getAll().map(
            records -> records.stream().map(UserDTO::apply).toList()
        ).map(this::success);
    }```
Or: Add custom response at route config

**Comment by Arkady-Dymkov** [comment]
Thank you! I'll close an issue)
