### ISSUE TITLE
Happen error while uploading file

### ISSUE THREAD

**Issue by anboo44** [activej/activej#285]
In my application, I use library `undici` to make a multipart/form-data request and send it to backend. I got error message:  `io.activej.common.exception.TruncatedDataException: Unexpected end-of-stream`. I debug and look into request, it seems is OK. 
When I sent request by tool `Insomania`, it was successful. I don't know why happen errror with: `undici` 

This is content-type of error request: `multipart/form-data; boundary=----formdata-undici-047766731364`
This is content-type of success request: `multipart/form-data; boundary=X-INSOMNIA-BOUNDARY`

<img width="1361" alt="Screen Shot 2023-06-06 at 22 01 39" src="https://github.com/activej/activej/assets/19175021/fabdd3f2-a1c9-4bcd-a38f-c4e944718561">

<img width="1009" alt="Screen Shot 2023-06-06 at 21 55 05" src="https://github.com/activej/activej/assets/19175021/97100688-45c6-4c4a-ab59-2d41b18238a1">

**Comment by eduard-vasinskyi** [comment]
Hi, @anboo44 
We have fixed the issue with multipart/form-data in the branch `master-5.5`. I have checked that multipart/form-data requests from `undici` now work correctly.

We plan to release version 5.5 soon, as well as version 6.0-beta1.

**Comment by anboo44** [comment]
@eduard-vasinskyi I will wait v5.5 and close this issue. Thanks
