### ISSUE TITLE
RPCClient lock port on local

### ISSUE THREAD

**Issue by nguyentamdat** [activej/activej#289]
I deployed 2 services: 1 RPC server and 1 RPC client on 1 host. The problem occurs when I started RPC client before RPC server had been started. If I don't set reconnectInterval for RPC client, it'll try to establish connect to local port and success after several try. After that, I can't start RPC server because that port already bind. I expect that RPC client doesn't establish connection to local port if not any application listen on that port.

**Comment by eduard-vasinskyi** [comment]
Hi, @nguyentamdat

`RpcClient` does not bind any address. Only servers can bind addresses. 
Maybe, there is another server running in your RPC client application? Could you please provide a demo application that demonstrates the issue?
