### ISSUE TITLE
Make classes Public to facilitate mocking.

### ISSUE THREAD

**Issue by akumaburn** [activej/activej#292]
Right now many of ActiveJ's classes and methods such as `HttpMessage.Builder` have protected designation (or private), this means that Mockito cannot be used to mock these classes or their methods, which limits the ability to integrate them for unit testing.

**Comment by eduard-vasinskyi** [comment]
Hi, @akumaburn

We designed classes with the encapsulation principle in mind. If you want to test or mock classes/methods that are not public, there are some ways to do that without changing the code under test: 

[How do I test protected methods?](https://junit.org/junit4/faq.html#atests_10) 
[How do I test private methods?](https://junit.org/junit4/faq.html#atests_11)
