### ISSUE TITLE
ActiveSpecializer links to ActiveCRDT

### ISSUE THREAD

**Issue by sirinath** [activej/activej#3]
I believe ActiveSpecializer links to the wrong link which is the ActiveCRDT page.

![image](https://user-images.githubusercontent.com/637415/85205067-59895600-b336-11ea-9575-ea834340a7e6.png)

So there should be descriptions and links to:
- ActiveSpecializer (description present but wrong link) and
- ActiveCRDT (no description present and ActiveSpecializer incorrectly links to this section)

links in the frontpage.

**Comment by sirinath** [comment]
@necauqua can this issue be fixed soon so that the full documentation is browsable as this does not require much effort since the documentation is already there?

**Comment by necauqua** [comment]
@valerialistratova is responsible for documentation and site layout and they will fix that as soon as possible

**Comment by valerialistratova** [comment]
@sirinath thanks for the suggestions! ActiveSpecializer link was updated. ActiveCRDT is in its beta yet, so we don't provide direct links to its website.
