### ISSUE TITLE
How to hook the end of the HttpResponse so I can clean up some buffers?

### ISSUE THREAD

**Issue by mikeg-red5hift** [activej/activej#304]
Hi. I just started using the ActiveJ HTTP server. It's a beautiful piece of engineering. Thanks.

I have an issue that maybe you can help with.

I am feeding the response a buffer, like so
```
HttpResponse response = HttpResponse.ok200()
.withHeader(CONTENT_TYPE, ofContentType(JSON_UTF_8))
.withBody(returnBuf).build();
```
The buffer is pooled, so I need to return it to the pool after the server is done with it. 

I can't find a hook where I can put my code to release the buffer to the pool. Everything I've tried results in the response using an empty buffer (i.e. a buffer that has already been cleared after returning to the pool.

For example, I tried using the `Promise<HttpResponse>.whenComplete()` method, but that seems to fire before the server has used the buffer and the server returns an empty response.

Is this possible, or will I have to stop using a buffer pool and let my buffers get GCed instead?  It does work properly when I do not return the buffers to the pool and they get GCed normally.

Thanks for your help.

**Comment by mikeg-red5hift** [comment]
I tried a few more things. I used ActiveJ's ByteBufPool instead of my own and everything appeared to work. However, I think that's because my pool implementation calls rewind() on the buffer when the buffer is recycled and ActiveJ's does not appear to. So, it looks like the response is pointing to a buffer that is "invalid" and in the queue to be handed out on subsequent requests. So, it's possible it could be modified by a second request before it gets a chance to access the bytes from the first request. So, it will probably fail to return the correct result on occasion?

I also got better throughput not recycling buffers at all. These are 8MB buffers, so I thought that was strange, but the results were consistent using WRK for load testing. So, maybe I will skip the buffer pool after all.

**Comment by eduard-vasinskyi** [comment]
Hi, @mikeg-red5hift

All of ActiveJ’s components utilize `ByteBufPool` to make sure that every ByteBuf gets recycled and returned to the pool once it is not needed anymore. 

When using ActiveJ HTTP, you do not need to worry about recycling ByteBufs manually. It is done automatically by `HttpServer` (or `HttpClient`). When you pass a ByteBuf to an HttpResponse (or HttpRequest when using HttpClient) you can be sure that it will be recycled and no data will be lost. This is something similar to an ownership (as in Rust language) of a ByteBuf. By setting a ByteBuf as a body of HttpResponse, you effectively pass the ownership to the HttpServer. And now it is its job to recycle the buffer properly.

ActiveJ components pass ByteBuf ownership between each other all the time. The only rule that should be maintained is that the last component that has the ownership of a ByteBuf should recycle that BuyteBuf.

You do not need to call the recycle() or rewind() methods manually. Moreover, you should not call any method on that ByteBuf once you return the HttpResponse, as the ByteBuf can already be recycled at that time.

The reason why the `recycle()` implementation does not “rewind” the buffer is that it is “rewinded” when it is allocated in the `ByteBufPool#allocate` method.

We would like to suggest that you use ByteBufPool for managing your ByteBufs.

**Comment by mikeg-red5hift** [comment]
Thank you for the clarification. That's a good design. I am using ByteBufPool now, so I'm all set.

**Comment by mikeg-red5hift** [comment]
I'm closing this issue. Thanks for the help.
