### ISSUE TITLE
Unknown characters when read messages from the websocket

### ISSUE THREAD

**Issue by Vynbz** [activej/activej#305]
Hi @eduard-vasinskyi, I saw that you have been away for several weeks, I hope you are doing well now.

I tried to communicate with the Discord websocket gateway using ActiveJ. I copied one of the examples (https://github.com/activej/activej/blob/master/examples/core/http/src/main/java/WebSocketEchoClientExample.java) and configured HttpClient to work over SSL.

Here's the Discord gateway url: "wss://gateway.discord.gg/?encoding=json&v=9&compress=zlib-stream".

What I wanted to achieve:
1. Read all incoming messages from the websocket.
2. Send everything from System.in to the websocket. (I didn't have any problems with that)

I don't know Active well, so to get type of each message, I ran this code in a new thread. Perhaps there is a better way to asynchronously read them.

`reactor.submit(() -> webSocket.messageReadChannel().streamTo(ChannelConsumers.ofConsumer(m -> { System.out.println(m.getType()); }))).get();`

After I have determined that the message type is BINARY I replaced the type printing with the content printing.

`new String(m.getBuf().array(), StandardCharsets.UTF_8)`

In the first message I got the HTTP version, headers and a set of chars in a unknown encoding instead of JSON. Other messages were just set of unknown-encoding chars. I tried to decrypt the messages using Inflater, but got "unknown compression method"/"incorrect header check" errors.

**Comment by eduard-vasinskyi** [comment]
Hi, @Vynbz 

The `ByteBuf#array` method returns ByteBuf’s underlying array as-is, without considering `head` or `tail` pointers. As ByteBufs are constantly reused, there is a high chance that ByteBuf’s internal array would contain any kind of data, like HTTP headers, etc. You should consider ByteBuf’s actual data to start from the `head` and end with the `tail` index.

To get an actual String from a ByteBuf, there are 2 methods `ByteBuf#getString(Charset)` and `ByteBuf#asString(Charset)`. The difference is that the first method simply converts a current ByteBuf to a String, while the second one also recycles the `ByteBuf`. When working with WebSocket, you should use the `asString()` method to print out message contents, as long as you do not plan to use that ByteBuf elsewhere.
