### ISSUE TITLE
HttpServer under PrimaryServer can't handle SSL requests

### ISSUE THREAD

**Issue by Vynbz** [activej/activej#312]
I am trying to run something like [MultithreadedHttpServerLauncher](https://github.com/activej/activej/blob/master/launchers/http/src/main/java/io/activej/launchers/http/MultithreadedHttpServerLauncher.java) to handle SSL requests. Everything is fine if I use pure HttpServer without PrimaryServer and set SSLContext for it directly, but in other cases, I get a NullPointerException error:

>java.lang.NullPointerException: Cannot invoke "javax.net.ssl.SSLContext.createSSLEngine()" because "sslContext" is null

After investigating, I found out that the doAccept method in AbstractReactiveServer is called with ssl=true, but SSLContext=null.

New request invokes doAccept(SocketChannel channel, InetSocketAddress localAddress, boolean ssl) method of PrimaryServer with ssl=true.
After that, all worker servers accept the connection judging by this line:
workerServerReactor.execute(() -> workerServer.doAccept(channel, localAddress, remoteSocketAddress, ssl, socketSettings));
This is where the error occurs, because all worker servers (which are HttpServer) do not have SSLContext, which means they cannot serve SSL connections.
In other words, if you set breakpoint [here](https://github.com/activej/activej/blob/1d3262206f560a6713cd37a5ee35dbaaed461449/core-net/src/main/java/io/activej/net/AbstractReactiveServer.java#L372), you will get such a result:

> this = HttpServer
> sslContext = null
> ssl = true

```
    @Provides
    WorkerPool workerPool(WorkerPools workerPools) {
        return workerPools.createPool(Scope.of(ContentServerScope.class), WORKERS);
    }

    @Provides
    PrimaryServer sslServer(NioReactor reactor, WorkerPool.Instances<HttpServer> httpServers, SSLContext sslContext) {
        return PrimaryServer.builder(reactor, httpServers)
                .withSslListenAddress(sslContext, Executors.newCachedThreadPool(), new InetSocketAddress(...))
                .build();
    }

    @Provides
    @ContentServerScope
    HttpServer contentServer(NioReactor reactor, RoutingServlet defaultServlet) {
        return HttpServer.builder(reactor, defaultServlet)
                .build();
    }
```

**Comment by eduard-vasinskyi** [comment]
Hi, @Vynbz

For now, you can set `SSLContext` and SSL `Executor` for both `PrimaryServer` (by specifying SSL listen addresses) and worker servers (without specifying actual listen addresses).

You can do that by using the `withSslListenAddresses(SSLContext sslContext, Executor sslExecutor, InetSocketAddress... addresses)` method of the server builder and passing `SSLContext`, `Executor` and no addresses. You only need to specify SSL listen addresses for the `PrimaryServer`.

We will try to find a better solution to the problem.
