### ISSUE TITLE
Support self define ThreadFactory for eventloop threads

### ISSUE THREAD

**Issue by segment11** [activej/activej#316]
I want to use AffinityThreadFactory instead of default in class ServiceAdapters.

Thanks.

**Comment by eduard-vasinskyi** [comment]
Hi, @segment11
There is the `ServiceAdapter<Eventloop> forEventloop(ThreadFactory threadFactory)` method in the `ServiceAdapters` class.
https://github.com/activej/activej/blob/2be70ecebfc3fbffc297987d084fef7f6ddf0e5c/boot-servicegraph/src/main/java/io/activej/service/adapter/ServiceAdapters.java#L274
You can use your preferred ThreadFactory like this:
```java
AffinityThreadFactory affinityThreadFactory = new AffinityThreadFactory("AffinityThreadFactory");
ServiceGraphModule serviceGraphModule = ServiceGraphModule.builder()
   .with(Eventloop.class, ServiceAdapters.forEventloop(affinityThreadFactory))
   .build();
```
