### ISSUE TITLE
Getting post parameters does not work

### ISSUE THREAD

**Issue by Vynbz** [activej/activej#317]
Hi, @eduard-vasinskyi 
I used the code from the example:
https://activej.io/http/examples#request-parameters-example

My code:
```
        return httpRequest -> httpRequest.loadBody()
                .then($ -> {
                    System.out.println($.getString(StandardCharsets.UTF_8));
                    System.out.println(httpRequest.getPostParameters().size());
                    final String username = httpRequest.getPostParameter("username");
                    final String password = httpRequest.getPostParameters().get("password");
                    System.out.println(username);
                    System.out.println(password);
                    return HttpResponse.ok200()
                            .withPlainText("test")
                            .toPromise();
                });
```

Output when Im sending a POST request:
> username=test&password=test
> 0
> null
> null

What am I doing wrong?

**Comment by eduard-vasinskyi** [comment]
Hi, @Vynbz

The `HttpRequest#getPostParameters` method checks whether the request contains a `Content-Type` header set to `application/x-www-form-urlencoded`. It should be automatically added if the request is sent using HTML form.

Could you verify that the HTTP request you send to the server has that header set?

You can add:
```java
System.out.println(request.getHeader(HttpHeaders.CONTENT_TYPE));
```
