### ISSUE TITLE
Inject instances as fields, not parameters

### ISSUE THREAD

**Issue by Vynbz** [activej/activej#318]
Hi, @eduard-vasinskyi 

I need a way to inject dependencies into my provider classes without using constructors, similar to how Spring's Autowired annotation works. At least, I want to simplify my current solution.

Currently, I have provider classes that extend AbstractModule and provide instances of certain classes. For example, one provider class provides an instance of Repository, and another provider class depends on that Repository instance.

Here's an example of what the code looks like:
```
    public final class ProviderA extends AbstractModule {
        private Dependency dependency;

        public ProviderA(Dependency dependency) {
            this.dependency = dependency;
        }

        @Provides
        private Instance instance() {
            return new Instance(dependency);
        }

    }
```
And I want to inject the "Instance" into another provider:
```
    public final class ProviderB extends AbstractModule {
        private Instance instance;

        public ProviderB(Instance instance) {
            this.instance = instance;
        }

    }
```
However, I have many dependencies and instances, and I don't want to pass them all as constructor parameters. Is there a way to inject them as fields instead?

My current working solution involves creating an Injector instance and binding the providers manually:
```
    final Injector injector = Injector.of(new DependencyProvider(), ModuleBuilder.create()
            .bind(ProviderA.class)
            .build());
            
    final Injector injector1 = Injector.of(injector.getInstance(ProviderA.class), ModuleBuilder.create()
            .bind(ProviderB.class)
            .build());
```
I have lots of providers, so this code will become super big. But I'd like to find a way to make this code more concise and easier to maintain.

**Comment by eduard-vasinskyi** [comment]
Hi, @Vynbz  
I don't quite get the question. If you want to inject classes without using constructor parameters, you could do something like that:
```java
@Provides
MyClass myClass(Dependency1 dependency1, Dependency2 dependency2){
   MyClass myClass = new MyClass();
   myClass.setDependency1(dependency1);
   myClass.setDependency2(dependency2);
   return myClass;
}
```


But you would still have a `myClass` method which takes multiple parameters. Alternatively, you could use manual binding to inject an array of dependencies:
```java
bind(MyClass.class).to(dependencies -> {
         MyClass myClass = new MyClass();
         myClass.setDependency1((Dependency1) dependencies[0]);
         myClass.setDependency2((Dependency2) dependencies[1]);
         return  myClass;
      },
      new Key[]{Key.of(Dependency1.class), Key.of(Dependency2.class)});
```
