### ISSUE TITLE
[Question] Redis Client

### ISSUE THREAD

**Issue by a1730** [activej/activej#32]
Hi,
Thank you for this excellent product/project. 
We are having much fun with it.

Could you please point us to a tutorial on how on one might create a Redis, or redis-like (connector) client?
We could take a wack at it but comparing your [SSE demo](https://gist.github.com/eduard-vasinskyi/65287c900a70288a1b298a9027b26ca5) code to our embarassing attempt to implement SSE without guidance tells us to ask for "professional help:)" Thank you for that code gist.

Generally, we are looking  to leverage ActiveJ for for interactions with Redis and PostgreSQL (JDBC). Any tutorial about creating this type of connectors with ActiveJ would be welcome.

Thanks again for a clean and awesome project.
Yes, we are using ActiveJ!

**Comment by a1730** [comment]
Would a JDBC client look like [this implementation in config test](boot-config/src/test/java/io/activej/config/EffectiveConfigTest.java)?
We could use that template, if approved, for our connectors...
Thank you.

**Comment by eduard-vasinskyi** [comment]
Hello, @a1730. We are currently developing our own high-performance asynchronous Redis client that utilizes ActiveJ's networking module. Stay tuned for the new releases!

**Comment by eduard-vasinskyi** [comment]
As for JDBC client, you can use an external thread pool for JDBC calls.

If you want to call some blocking code from inside of the eventloop thread, you can wrap the blocking code in `Promise.ofBlockingCallable()` / `Promise.ofBlockingRunnable()`. 
You need to pass an external Executor which will run blocking code as well as blocking Runnable or Callable. If blocking code throws any checked exception, the resulting promise will be completed exceptionally with propagated exception. 

Here's an example of how you can use `Promise.ofBlockingCallable()` to make JDBC calls: https://gist.github.com/eduard-vasinskyi/ba4c81fc063300e0c46bc57dc2b10b05

**Comment by a1730** [comment]
Good,
This is the approach we have been using with our DAOs; in fact, we started from that gist. Looks like we're doing something right.
Thank you for the feedback.

**Comment by a1730** [comment]
> 
> 
> Hello, @a1730. We are currently developing our own high-performance asynchronous Redis client that utilizes ActiveJ's networking module. Stay tuned for the new releases!

I know it's  going to be good. Can't wait.
I'll be on the lookuout for the release.
Thank you.
We're going broke on activej!

**Comment by a1730** [comment]
Hi @eduard-vasinskyi ,
> 
> Hello, @a1730. We are currently developing our own high-performance asynchronous Redis client that utilizes ActiveJ's networking module. Stay tuned for the new releases!

It looks like  cloud-redis did not make the cut for 3.0,  it is not in the 3.1 master git branch, but still hidden in the redis-client branch. We trust that you have very good reasons for the priorities. However, if this were a democracy we would gladly up-vote that feature if requested😄 

Thank you.

**Comment by eduard-vasinskyi** [comment]
Hello, @a1730 
We have finished implementing the first version of ActiveJ’s Redis client. You can get familiar with the API in branch [redis-client](https://github.com/activej/activej/tree/redis-client). Right now it supports most of [String](https://redis.io/commands#string), [List,](https://redis.io/commands#list) [Set](https://redis.io/commands#set), [SortedSet](https://redis.io/commands#sorted_set), [Hash](https://redis.io/commands#hash), [Geo](https://redis.io/commands#geo), and [HyperLogLog](https://redis.io/commands#hyperloglog) commands. It supports pipelining, transactions, and TLS. You can look at [tests](https://github.com/activej/activej/tree/redis-client/cloud-redis/src/test/java/io/activej/redis)/[benchmarks](https://github.com/activej/activej/tree/redis-client/benchmarks/redis) to get an idea of how to use the API.
Redis-client will be part of the version 4.0 release, which is about to be released. More examples/documentation will be provided upon release.
If you have any API, commands suggestions please let us know. We might either add them prior to the 4.0 release or in future versions.

**Comment by a1730** [comment]
Hello @eduard-vasinskyi ,
Thank you so much for this module. We have been beating up on it, and it has satisfied our redis use cases.
We are not sophisticated Redis users so it will take some time before we need fancy commands. Thank you for the offer, we are appreciative.
Thank you.
