### ISSUE TITLE
Implement attribute system for HttpRequest

### ISSUE THREAD

**Issue by Vynbz** [activej/activej#323]
Hi, @eduard-vasinskyi

Can you implement an attribute map system for HttpRequest in ActiveJ, similar to Netty's ChannelHandlerContext attribute map? This feature is needed to avoid violating the DRY principle in AsyncServlet chains, particularly when passing data like JWT IDs between servlets.

Currently, we have to double-fetch the Authorization header in scenarios like this:
```
public final class ExampleFilter implements AsyncServlet {
    AsyncServlet next;

    public ExampleFilter(AsyncServlet next) {
        this.next = next;
    }

    @Override
    public Promise<HttpResponse> serve(HttpRequest request) throws Exception {
        // Parse JWT here
        String jwt = request.getHeader(HttpHeaders.AUTHORIZATION)
        // ... JWT processing ...

        return next.serve(request);
        // The next servlet doesn't know about the JWT processing
        // and might need to fetch and process the Authorization header again
    }
}
```
With an attribute map, we could store the processed JWT data and make it available to subsequent servlets without repeating the header fetch and processing.

**Comment by eduard-vasinskyi** [comment]
Hi, @Vynbz

You could use `HttpMessage#attach` and `HttpMessage#getAttachment` for managing request/response context across AsyncServlet chains.

https://github.com/activej/activej/blob/de8324df32b43a9c4e80a6aae816c142cba0caae/core-http/src/main/java/io/activej/http/HttpMessage.java#L395-L402

https://github.com/activej/activej/blob/de8324df32b43a9c4e80a6aae816c142cba0caae/core-http/src/main/java/io/activej/http/HttpMessage.java#L440-L450
