### ISSUE TITLE
Sub Menu Linking to Different Pages

### ISSUE THREAD

**Issue by sirinath** [activej/activej#40]
For ease of navigation can we have sub menus.

![image](https://user-images.githubusercontent.com/637415/104998429-3bf9a780-5a51-11eb-920b-3ef989af4360.png)

**Comment by eduard-vasinskyi** [comment]
Hello, @sirinath 
I do not quite understand what sub-menus are you talking about? All of the links here lead to separate websites.

**Comment by sirinath** [comment]
You can have something like:
- ActiveJ
  - Tutorials
    - Getting Started
    - ...
  - Async I/O
    - ...
  - ...
- ...

**Comment by eduard-vasinskyi** [comment]
@sirinath
Thank you for the suggestion. We will look into it when we will do a redesign of a website.

**Comment by eduard-vasinskyi** [comment]
The [website](https://activej.io/) was redesigned, so closing this issue.
