### ISSUE TITLE
Framing Package

### ISSUE THREAD

**Issue by azzahrah** [activej/activej#42]
Is this available framing packet option? like split by length of header?

**Comment by eduard-vasinskyi** [comment]
@azzahrah 
Sorry, I didn't quite understand your question. Could you please explain what you meant?

**Comment by azzahrah** [comment]
Like in netty:
[https://netty.io/4.0/api/io/netty/handler/codec/ByteToMessageDecoder.html](url)
or 
[https://netty.io/4.0/api/io/netty/handler/codec/FixedLengthFrameDecoder.html](url)

above class can delimeter incomming packet base on length of header, or delimeter base on \r\n

**Comment by azzahrah** [comment]
mybe this what i want

`
 static ByteBufsDecoder<ByteBuf> customDecoder(int maxSize) {
        return bufs -> {
            int bytes = bufs.scanBytes(new ByteBufQueue.ByteScanner() {
                boolean crFound;

                @Override
                public boolean consume(int index, byte b) throws MalformedDataException {
                    if (crFound) {
                        if (b == LF) {
                            return true;
                        }
                        crFound = false;
                    }
                    if (index == maxSize - 1) {
                        throw new MalformedDataException("No CRLF is found in " + maxSize + " bytes");
                    }
                    if (b == CR) {
                        crFound = true;
                    }
                    return false;
                }
            });

            if (bytes == 0) {
                return null;
            }

            ByteBuf buf = bufs.takeExactSize(bytes);
            buf.moveTail(-2);
            return buf;
        };
    }
`

**Comment by eduard-vasinskyi** [comment]
Hello, @azzahrah
Could you describe your scenario in more detail? That way we could help you pick up the most suitable components for your task.

For starters, you could probably use [ChannelFrameEncoder](https://github.com/activej/activej/blob/master/core-csp/src/main/java/io/activej/csp/process/frames/ChannelFrameEncoder.java)/[ChannelFrameDecoder](https://github.com/activej/activej/blob/master/core-csp/src/main/java/io/activej/csp/process/frames/ChannelFrameDecoder.java). Just implement your own [FrameFormat](https://github.com/activej/activej/blob/master/core-csp/src/main/java/io/activej/csp/process/frames/FrameFormat.java), based on your protocol. There are also some available formats in [FrameFormats](https://github.com/activej/activej/blob/master/core-csp/src/main/java/io/activej/csp/process/frames/FrameFormats.java). Like size-prefixed format, or a format with a custom magic number.
You can look at [FrameFormatTest](https://github.com/activej/activej/blob/master/core-csp/src/test/java/io/activej/csp/process/frames/FrameFormatTest.java) as a reference.

**Comment by azzahrah** [comment]
@eduard-vasinskyi ,

thanks for your answer, we have data send by GPS Tracker device to my server, and this procotocol:

Server GPS
```
public final class TcpServerExample {

    private static final int PORT = 9922;
    public static void main(String[] args) throws Exception {
        Eventloop eventloop = Eventloop.create().withCurrentThread();
        SimpleServer server = SimpleServer.create(eventloop, new Consumer<AsyncTcpSocket>() {
            @Override
            public void accept(AsyncTcpSocket socket) {

                // readData(socket);
                BinaryChannelSupplier
                        .of(ChannelSupplier.ofSocket(socket))
                        .decodeStream(decodergt06.decoder(1024))
                        .streamTo(ChannelConsumer.ofConsumer((data) -> {
                            byte[] bytes = new byte[data.tail()];
                            data.read(bytes);
                            System.out.println(Utils.toHex(bytes));
                            data.recycle();             
                            System.out.println("Number of ByteBufs in pool after recycling: " + ByteBufPool.getStats().getPoolItems());
                        }));
            }
        });
        server.withListenPort(PORT);
        server.listen();

        System.out.println("Server is running");
        System.out.println("You can connect from telnet with command: telnet localhost 9922 or by running csp.TcpClientExample");

        eventloop.run();
    }
    //[END REGION_1]
}
```

Decoder
```
public class decodergt06 {

    /*
        Decoder GT06
        Header      2Byte 0x78 0x78
        Length      1Byte 1A (Length = Protocol Number + Information Content + Information Serial Number + Error Check)
        protocol    1Byte
        Content     NByte
        Serial      2Byte
        Error Check 2Byte
        Tail        2Byte 0xD 0xA
        
     */
    public static ByteBufsDecoder<ByteBuf> decoder(int maxSize) {
        return new ByteBufsDecoder<ByteBuf>() {
            @Override
            public ByteBuf tryDecode(ByteBufQueue bufs) throws MalformedDataException {
                if (bufs.hasRemainingBytes(5)) {
                    return null;
                }              
                int length = 2 + 2; //header tail
                if (bufs.peekByte(0) == 0x78 && bufs.peekByte(1) == 0x78) {
                    length += 1 + bufs.peekByte(2);
                } else if (bufs.peekByte(0) == 0x79 && bufs.peekByte(1) == 0x79) {
                    length += 2 + bufs.peekByte(2);
                }
                
                if (bufs.hasRemainingBytes(length)) {
                    return null;
                }
                return bufs.takeExactSize(length);
            }
        };
                
    }
}

```
i don't know is above away best usage your component to solve my problem?

in Server GPS after read data i alway call data.recycle();  

so to read next incoming data i always check header by bufs.peekByte(0) and by bufs.peekByte(1) like below

if (bufs.peekByte(0) == 0x78 && bufs.peekByte(1) == 0x78) <--- is this right away?

**Comment by eduard-vasinskyi** [comment]
@azzahrah You may decode bytebufs to any type by using [ByteBufsDecoder\<T\>](https://github.com/activej/activej/blob/master/core-csp/src/main/java/io/activej/csp/binary/ByteBufsDecoder.java). For example, you can transform incoming bufs into hex string based on your protocol. 

To transform ByteBuf into an array you can use its methods `getArray()` (does not recycle buf) and `asArray()` (does recycle buf).

As for parsing headers, you indeed may use `ByteBufQueue::peekByte`. Peeking a few bytes is fine, but if you need to peek a lot of bytes you should use `ByteBufs::scanBytes` as `peekByte()` may have some performance issues.
Also, the condition when checking for remaining bytes should be inverted. You need to return `null` if queue does NOT have enough bytes.


Here is an updated example with some header validation:
Server:
```
SimpleServer server = SimpleServer.create(eventloop, socket -> {
	BinaryChannelSupplier
			.of(ChannelSupplier.ofSocket(socket))
			.decodeStream(decodergt06.decoder())
			.streamTo(ChannelConsumer.ofConsumer(System.out::println));
});
 ```

Decoder:
```
public static ByteBufsDecoder<String> decoder() {
  return bufs -> {
     if (!bufs.hasRemainingBytes(3)) {
        return null;
     }
     int length = 2 + 2; //header tail
     byte byte0 = bufs.peekByte(0);
     byte byte1 = bufs.peekByte(1);
     if (byte0 == 0x78 && byte1 == 0x78) {
        length += 1 + bufs.peekByte(2);
     } else if (byte0 == 0x79 && byte1 == 0x79) {
        length += 2 + bufs.peekByte(2);
     } else {
        throw new MalformedDataException("Invalid header: " + byte0 + ", " + byte1);
     }
 
     if (!bufs.hasRemainingBytes(length)) {
        return null;
     }
     ByteBuf buf = bufs.takeExactSize(length);
     byte[] array = buf.asArray(); // asArray() recycles buf
     return Arrays.toString(array);  
   };
}
```
If you need ultimate performance you can look at our [Redis client implementation](https://github.com/activej/activej/tree/master/extra/cloud-redis). It does not use ByteBufQueue class but appends all the incoming data to a single ByteBuf. We have managed to get twice the performance of Jedis with this approach.

**Comment by azzahrah** [comment]
@eduard-vasinskyi , thank for your answer, those really help me....  i will try learn redis  client component.. as you sugest
