### ISSUE TITLE
ByteBuf leak detector

### ISSUE THREAD

**Issue by azzahrah** [activej/activej#45]
any feature to give warning when ByteBuf leak occured, like in netty?

**Comment by eduard-vasinskyi** [comment]
Hello, @azzahrah 
Leaked ByteBufs will still be collected during GC, explicit recycling is used for reducing memory pressure. You can detect leaks during unit tests by using the JUnit rule [ByteBufRule](https://github.com/activej/activej/blob/master/test/src/main/java/io/activej/test/rules/ByteBufRule.java) which will fail if there are unrecycled bufs after the test.

At the runtime, you can detect  ByteBuf leaks by observing ByteBuf pool stats either via JMH or by obtaining stats like this: `ByteBufPool.getStats()`. First, you need to enable additional pool statistics by running your application with VM option `-DByteBufPool.stats=true`. If the number of created items consistently increases during the application lifecycle, there are probably some unrecycled ByteBufs. 

You may also obtain a map of unrecycled ByteBufs with stack traces of their creation. To do so, you need to enable the VM option `-DByteBufPool.registry=true`. Then call `getUnrecycledBufs()` on the `BytBufPoolStats` object.
Note, that setting these VM options may greatly slow down buf allocation/recycling, so use it only for debugging purposes.

**Comment by azzahrah** [comment]
@eduard-vasinskyi , thanks for your answer, it is really help me to explore activeJ component
