### ISSUE TITLE
ByteBuf read unsigned value?

### ISSUE THREAD

**Issue by azzahrah** [activej/activej#46]
after learn ByteBuf class,  i can't find function to read unsigned value like:
buf.getUnsignedByte()
buf.getUnsignedShort();
buf.getUnsignedInt()
... etc

or this not available yet?

**Comment by eduard-vasinskyi** [comment]
There is no difference in signed/unsigned encoding. You can simply read signed data from ByteBuf and convert it to unsigned like this: `Integer.toUnsignedLong(buf.readInt())` etc.

**Comment by azzahrah** [comment]
@eduard-vasinskyi , thank for you answer...
