### ISSUE TITLE
activej-bytebuf 4.0-rc1 error in pom.xml

### ISSUE THREAD

**Issue by azzahrah** [activej/activej#48]
I can't download activej-bytebuf 4.0-rc1, below is my setting in pm.xml
``` 
 <dependency>
            <groupId>io.activej</groupId>
            <artifactId>activej-bytebuf</artifactId>
            <version>4.0-rc1</version>
        </dependency>

```

**Comment by eduard-vasinskyi** [comment]
Hello, @azzahrah 
I've just tested locally and the dependency had successfully been downloaded.
Plus, the jar is present in [Maven Repository](https://mvnrepository.com/artifact/io.activej/activej-bytebuf/4.0-rc1)

**Comment by eduard-vasinskyi** [comment]
@azzahrah 
There has been a release of ActiveJ 4.0. Do you still have trouble adding it to your project?

**Comment by azzahrah** [comment]
@eduard-vasinskyi , thank very much... finally its working now...
