### ISSUE TITLE
APIs and Modules for Better Client/Browser/Front-end and Web Server/Back-end Communication 

### ISSUE THREAD

**Issue by sirinath** [activej/activej#5]
This is collating of related issues I opened at DataKernal requesting to support:
- WebSockets https://github.com/softindex/datakernel/issues/19
- Server-Sent Events https://github.com/softindex/datakernel/issues/23
- Other technologies for client/browser/front-end and Web Server/Back-end Communication https://github.com/softindex/datakernel/issues/22

The 1st 2 WebSockets and Server-Sent Events is highly desired.

**Comment by valerialistratova** [comment]
We’ve introduced support for Websockets in ActiveJ v2.1. As for the SSE and other suggestions, you can check the corresponding answers on the DataKernel repository. Thanks!
