### ISSUE TITLE
BosGroup and WorkerGroup

### ISSUE THREAD

**Issue by azzahrah** [activej/activej#51]
i know In netty to launch TCP server we just configure BootstrapServer and passed BossGroup (To receive connection) and WorkerGroup(To process event, like read data, write data), howto archive that in activej... and howto set how manu eventloop in boosGroup and in WorkerGroup

**Comment by eduard-vasinskyi** [comment]
Hello, @azzahrah
ActiveJ’s common threading model consists of one Primary eventloop that is used for accepting requests and dispatching them to Worker eventloops. Each eventloop runs in its own thread.
You may take a look at [PrimaryServer](https://github.com/activej/activej/blob/master/core-net/src/main/java/io/activej/net/PrimaryServer.java) which actually dispatches requests between some number of [WorkerServer](https://github.com/activej/activej/blob/master/core-net/src/main/java/io/activej/net/WorkerServer.java)s. You can create and manage those servers manually or you can use ActiveJ Inject to handle it for you. There is a default convenient [WorkerPoolModule](https://github.com/activej/activej/blob/master/boot-workers/src/main/java/io/activej/worker/WorkerPoolModule.java) that handles the lifecycle of ‘worker’ components (Eventloops, WorkerServers, etc.). You may take a look at [MultithreadedHttpServerLauncher](https://github.com/activej/activej/blob/master/launchers/http/src/main/java/io/activej/launchers/http/MultithreadedHttpServerLauncher.java) as an example. It is quite straightforward, all you need to do is set up the required number of workers you need, and annotate worker components with `@Worker` annotation.

**Comment by azzahrah** [comment]
@eduard-vasinskyi finally we have implement TCP server with workerpool... thanks
