### ISSUE TITLE
getPathParameter not give me value

### ISSUE THREAD

**Issue by azzahrah** [activej/activej#56]
Why getPathParameter not give me value but paramete string like id_user=1
```
 @Provides
    AsyncServlet createServlet() {
        return RoutingServlet.create()
                .map(HttpMethod.POST,"/vehicle/list/:id_user",r->{
                    String id_user="";
                    try{
                        id_user=r.getPathParameter("id_user");
                    }catch (Exception ex){
                        ex.printStackTrace();
                    }
                    return HttpResponse.ok200().withPlainText("Value = "+ id_user);
                });
    }
```
when i send http://localhost:8080/vehicle/list/id_user=1

output

```
  Value = id_user=1
```
My expectation is  Value = 1

**Comment by eduard-vasinskyi** [comment]
Hello, @azzahrah 
You actually do not need to specify `id_user=1` in your URL. Just use http://localhost:8080/vehicle/list/1 As everything that goes after `.../list/` would be mapped as path parameter `id_user`.

You also do not need to wrap `getPathParameter()` in a try-catch block. It would throw `IllegalArgumentException` only if you messed up in setting up paths in a `RoutingServlet`. But you have `/:id_user` mapped, so retrieving a path parameter `id_user` would never throw an exception here.

**Comment by azzahrah** [comment]
@eduard-vasinskyi, thank you very much... really help me.....

**Comment by eduard-vasinskyi** [comment]
We have updated [RoutingSrevletExample](https://github.com/activej/activej/blob/master/examples/core/http/src/main/java/RoutingServletExample.java) by adding request routing  based on path parameters
