### ISSUE TITLE
MultipartFormData Handle

### ISSUE THREAD

**Issue by azzahrah** [activej/activej#58]
any tutorial to handle MultipartFormData? i need decode multiple Fields and File in multithread?, what exactly decoder to handle it?

**Comment by eduard-vasinskyi** [comment]
Hello, @azzahrah 
We have added an [example](https://github.com/activej/activej/blob/master/examples/core/http/src/main/java/MultipartDataHandlingExample.java) of handling MultipartFormData.
To handle multipart data you need to call https://github.com/activej/activej/blob/c659f8cc638aaf778476f6c775a87eb664b50799/core-http/src/main/java/io/activej/http/HttpRequest.java#L342
method and pass a `MultipartDataHandler`. 

How do you need to handle fields and files?
There are several predefined handlers in `MultipartDataHandler`. If you need to handle both fields and files you may use
`MultipartDataHandler#fieldsToMap(map, uploadFn)` - it collects all the fields sent in the request into a provided `Map`, uploading the files to some [ChannelConsumer](https://github.com/activej/activej/blob/master/core-csp/src/main/java/io/activej/csp/ChannelConsumer.java) obtained based on the filename.

If that is not enough, you may implement a custom `MultipartDataHandler` that suits your task. You will need to implement 2 methods:
 `Promise<ChannelConsumer<ByteBuf>> handleField(String fieldName)`
and
 `Promise<ChannelConsumer<ByteBuf>> handleFile(String fieldName, String fileName)`
If you need help with that, feel free to ask. Or you may look at `MultipartDataHandler` implementations for reference.

**Comment by azzahrah** [comment]
@eduard-vasinskyi thank for fast response,, this really help...  this enough to learn activej-multipart...
