### ISSUE TITLE
Question - How to get POST body as InputStream

### ISSUE THREAD

**Issue by FireMasterK** [activej/activej#66]
Title,
```
        .map(HttpMethod.POST, "/webhooks/pubsub", request -> {
            request.getBodyStream(); // returns a ChannelSupplier<ByteBuf>
        })
```
Is there any way to get the Body as an `InputStream`?

**Comment by eduard-vasinskyi** [comment]
Hello, @FireMasterK
The blocking nature of `InputStream/OutputStream` contradicts ActiveJ's asynchronous approach. You could use [ChannelSupplier](https://github.com/activej/activej/blob/master/core-csp/src/main/java/io/activej/csp/ChannelSupplier.java)/[ChannelConsumer ](https://github.com/activej/activej/blob/master/core-csp/src/main/java/io/activej/csp/ChannelConsumer.java)as an asynchronous alternative to java’s IO streams.
 
Or you could load the body completely asynchronously (via `HttpResponse#loadBody` method) and then wrap a byte array of resulting [ByteBuf](https://github.com/activej/activej/blob/master/core-bytebuf/src/main/java/io/activej/bytebuf/ByteBuf.java) into `ByteArrayInputStream`.
 
As a last resort, you could use an adapter https://github.com/activej/activej/blob/9f296dac9806a41ebcec8159e5a37dd0f48e2fac/core-csp/src/main/java/io/activej/csp/ChannelSuppliers.java#L334 You need to pass an [Eventloop](https://github.com/activej/activej/blob/master/core-eventloop/src/main/java/io/activej/eventloop/Eventloop.java) instance alongside `ChannelSupplier`. `Eventloop` can be obtained using `Eventloop.getCurrentEventloop()` (assuming being called from within `Eventloop` thread).


**Note, that the resulting InputStream read methods are blocking, so they should be called from some external thread, as not to block Eventloop**

**Comment by FireMasterK** [comment]
Thank you!

But I'm a bit confused, aren't these run on worker threads? Shouldn't it be ok to perform io operations on them?

**Comment by eduard-vasinskyi** [comment]
If you are talking about [MultithreadedHttpServerLauncher](https://github.com/activej/activej/blob/master/launchers/http/src/main/java/io/activej/launchers/http/MultithreadedHttpServerLauncher.java), there is a fixed number of worker threads. A worker thread is actually a worker `Eventloop` Each new request is dispatched to the worker `Eventloop` in a round-robin manner. So, if one such worker thread blocks, it would also postpone the execution of the following requests.

Avoid excessive blocking of Eventloop threads. For everything else, you can use regular Java multithreading capabilities.

You can read more about the ActiveJ threading model [here](https://activej.io/workers.html)

**Comment by FireMasterK** [comment]
Thank you! I will go through the documentation once again!
