### ISSUE TITLE
Adding headers to StaticServlet Responses

### ISSUE THREAD

**Issue by Kilobyte1000** [activej/activej#67]
I was trying to add cache-control headers to StaticServlet responses, but it always returns null: 
```
StaticServlet.ofClassPath(executor, "/public/")
	/* index resources */
	.serve(httpRequest)
	.getTry()    //null
	.getOrThrow()    //NPE
```
How can I add headers without directly obtaining the response?

**Comment by eduard-vasinskyi** [comment]
Hello, @Kilobyte1000 
You can use `StaticServlet#withResponse` method to specify a supplier of [HttpResponse](https://github.com/activej/activej/blob/master/core-http/src/main/java/io/activej/http/HttpResponse.java) which will be used when the resource is successfully loaded:
```
StaticServlet.ofClassPath(executor, "/public/")
    .withResponse(() -> HttpResponse.ok200()
        .withHeader(HttpHeaders.CACHE_CONTROL, HttpHeaderValue.of("max-age=30")))
```


However, this works only for a [StaticServlet](https://github.com/activej/activej/blob/master/core-http/src/main/java/io/activej/http/StaticServlet.java). A more general approach is wrapping a servlet and adding a header after the original servlet finishes serving:
```
@Provides
AsyncServlet servlet(Executor executor) {
    AsyncServlet original = StaticServlet.ofClassPath(executor, "/public/");
		
    return request -> original.serveAsync(request)
            .map(response -> response
                    .withHeader(HttpHeaders.CACHE_CONTROL, HttpHeaderValue.of("max-age=30")));
}

```
