### ISSUE TITLE
Question: UDP Server example 

### ISSUE THREAD

**Issue by ChungTak** [activej/activej#68]
I want to use activej to implement a udp server, which continuously receives data. But I can't find examples in the documentation and source code.

**Comment by eduard-vasinskyi** [comment]
Hello, @ChungTak
We have added examples that illustrate how to implement a custom [UDP ping client](https://github.com/activej/activej/blob/examples/examples/core/net/src/main/java/udp/UdpPingClientExample.java) and [UDP pong server](https://github.com/activej/activej/blob/examples/examples/core/net/src/main/java/udp/UdpPongServerExample.java).
