### ISSUE TITLE
'activej-di' is still '1.0-rc1' on Maven Central Published on 05 Jun 2020

### ISSUE THREAD

**Issue by sirinath** [activej/activej#7]
`activej-di` is still `1.0-rc1` on Maven Central. I am wondering if this in intentional of accidental where `1.0` was missed?

The other artefact has:
- `1.0-rc1` published on 05 Jun 2020
- `1.0-rc2` published on 09 Jun 2020
- `1.0` published on 12 Jun 2020

In the case these are missing artefacts can they be published?

**Comment by necauqua** [comment]
Hello, `activej-di` was renamed to `active-inject` on it's release.
