### ISSUE TITLE
Confused by eventloop worker thread name.

### ISSUE THREAD

**Issue by Youmoo** [activej/activej#70]
Hi. Sorry to disturb. I'm learning from activej source code. When I change [this line](https://github.com/activej/activej/blob/93c58decd3eeb1dc3978aca1ed2e4fa8253b5917/launchers/http/src/main/java/io/activej/launchers/http/MultithreadedHttpServerLauncher.java#L135) to:

```java
return request -> HttpResponse.ok200().withPlainText(Thread.currentThread().getName() + " => Hello, world! #" + workerId);
```
to check whether each request is handled in different threads. I find the returned thread name is confusing:

![image](https://user-images.githubusercontent.com/2532886/113963173-bae5cb80-985b-11eb-8e4c-c91b0881afca.png)

It is as if different worker threads runs in different thread pools. But the source code in `ServiceAdapters#forEventloop(ThreadFactory)` tells a different story:

```java
@Override
public CompletableFuture<?> start(Eventloop eventloop, Executor executor) {
	CompletableFuture<?> future = new CompletableFuture<>();
	threadFactory.newThread(() -> {
		eventloop.keepAlive(true);
		future.complete(null);
		eventloop.run();
	}).start();
	return future;
}
```
If I'm right, the eventloop worker does not belong to any thread pool.

So if that's true, can I make a PR to adjust `ServiceAdapters#forEventloop()` ? 

The PR will include one of the two implementations：

1. Make all eventloop threads use the same `ThreadFactory`
```java
public static ServiceAdapter<Eventloop> forEventloop() {
	ThreadFactory threadFactory = Executors.defaultThreadFactory();
	return forEventloop(r -> {
		Thread thread = threadFactory.newThread(r);
		thread.setName("eventloop: " + thread.getName());
		return thread;
	});
}
```
In this case，eventloop threads belongs to the same *virtual* pool.
![image](https://user-images.githubusercontent.com/2532886/113964006-372cde80-985d-11eb-8ea2-807688cc3c0c.png)

2. Replace `defaultThreadFactory()` with a custom one:
```java
public static ServiceAdapter<Eventloop> forEventloop() {
	DefaultThreadFactory threadFactory = new DefaultThreadFactory();
	return forEventloop(r -> {
		Thread thread = threadFactory.newThread(r);
		thread.setName("eventloop: " + thread.getName());
		return thread;
	});
}

/**
 * A modified version of java.util.concurrent.Executors.DefaultThreadFactory
 */
private static class DefaultThreadFactory implements ThreadFactory {
	private final ThreadGroup group;
	private final AtomicInteger threadNumber = new AtomicInteger(1);
	private final String namePrefix;

	DefaultThreadFactory() {
		SecurityManager s = System.getSecurityManager();
		group = (s != null) ? s.getThreadGroup() :
				Thread.currentThread().getThreadGroup();
		namePrefix = "thread-";
	}

	public Thread newThread(Runnable r) {
		Thread t = new Thread(group, r,
				namePrefix + threadNumber.getAndIncrement(),
				0);
		if (t.isDaemon())
			t.setDaemon(false);
		if (t.getPriority() != Thread.NORM_PRIORITY)
			t.setPriority(Thread.NORM_PRIORITY);
		return t;
	}
}
```
![image](https://user-images.githubusercontent.com/2532886/113965006-2ed5a300-985f-11eb-85f4-2488a12394a7.png)

Which do you prefer?

---

P.S. I know that we can use `Eventloop.withInitializer()` to customize thread name, but I think it will be better the default one  just works.

Sorry for my poor non-native english.

**Comment by eduard-vasinskyi** [comment]
Hello, @Youmoo
Thank you for investigating this issue. Apparently, `Executors.defaultThreadFactory()` creates a new `ThreadFactory` every time rather than returning some predefined factory.
We should be caching and reusing it for every new `Eventloop` thread. 
 
Could you please send a pull request containing the first implementation of a fix?
