### ISSUE TITLE
ActiveJ Redis client and Redis ACL.

### ISSUE THREAD

**Issue by a1730** [activej/activej#73]
The Redis client is working great for us. Thank you.
However, we enabled AUTH on the test server, and some hell broke loose. 

We added AUTH right after connecting but we seem to be missing something because Redis complains about AUTH for some of our requests. Even ActiveJ unit tests fail GETTTT/SETTT tests. We're still debugging the exception handler.
However a good majority of messages go through without issues. Any hints where to look?

Peripherally, is there a need for connection pooling or do we just throw multiple @Workers at it because this puppy is very robust (no dangling connections), and it is Real Fast(tm)?

Thank you for ActiveJ it has been a pleasure to work with.

**Comment by a1730** [comment]
Quick update.
First, all tests in RedisConnectionTestWithStub passed.
With RedisConnectionTestWithReal , we changed ActiveJ the test class from Github for call Redis GET - All test passed showing that connections are good and using Redis authentication. 
Redis CLIENT LIST command from redis-cli confirms that the ActiveJ client is connected, and operational.

However, the tests fail if we use RedisConnectionTestWithReal  from ActiveJ cloud-redis 4.1.1 test download from Github. 
The client hangs and we had to stop the tests.

BYW: this is what we did to the test connector:

``` static <T> T
  await(RedisClient client, Function<RedisConnection, Promise<T>> clientCommand) {
    return TestUtils.await(
      client.connect()
        .map(connection ->
          connection.cmd(RedisRequest.of("AUTH", "user", "supernsasecret!"), STRING)
            .mapEx((s, e) -> e == null && s.equalsIgnoreCase("OK") ?
              connection : new RuntimeException("Auth failure.", e))
            .then(() -> clientCommand.apply(connection)
              .thenEx((result, e) -> connection.quit()
                .then(() -> e == null ?
                  Promise.of(result) :
                  Promise.ofException(e)))).getResult()));
  }
```
What are we missing?
Thank you.

**Comment by a1730** [comment]
Hi,
This seems to be working for us.
```
private static <T> T
  await(Function<RedisConnection, Promise<T>> clientCommand) {
    if (!canConnect())  throw new RuntimeException("Redis connection is invalid");
    RedisClient client = RedisClient.create(Eventloop.create().withCurrentThread(), ADDRESS);
    return compute(
      client.connect()
        .then(connection -> connection.cmd(RedisRequest.of("AUTH", user, pass), SKIP)
          .then(() -> clientCommand.apply(connection))
          .thenEx((result, e) -> connection.quit()
            .then(() -> e == null ?
              Promise.of(result) :
              Promise.ofException(e)))));
  }
```
I wonder if there is a better way...
Thank you.
PS: RedisClient and RedisConnection are final classes.

**Comment by eduard-vasinskyi** [comment]
Hello, @a1730
We are glad to hear that you enjoy working with ActiveJ!
 
The problem with hanging tests is that after some command fails, the connection is not properly closed, leading to Eventloop still running as there are active TCP connections. What you can do is add `connection#close` call once authentication fails. Another option is to add `connection#close` call in `.whenException()` handler.
 
To run our tests with ACL, you should probably extract connect/auth code into an external method. Some tests in [RedisConnectionTestWithReal](https://github.com/activej/activej/blob/master/extra/cloud-redis/src/test/java/io/activej/redis/RedisConnectionTestWithReal.java) use multiple connections and call `client.connect()` for that reason. You can rewrite `await()` method in [TestUtils](https://github.com/activej/activej/blob/master/extra/cloud-redis/src/test/java/io/activej/redis/TestUtils.java) class like this:
```
public static <T> T await(RedisClient client, Function<RedisConnection, Promise<T>> clientCommand) {
  return io.activej.promise.TestUtils.await(connectAuth(client)
        .then(conn -> clientCommand.apply(conn)
              .thenEx((result, e) -> conn.quit()
                    .then(() -> e == null ?
                          Promise.of(result) :
                          Promise.ofException(e)))));
}
 
public static Promise<RedisConnection> connectAuth(RedisClient client) {
  return client.connect()
        .then(connection ->
              connection.cmd(RedisRequest.of("AUTH", "test", "pass"), RedisResponse.STRING)
                    .thenEx((s, e) -> {
                      if (e == null && s.equalsIgnoreCase("OK")) {
                            return Promise.of(connection);
                      }
 
                      connection.close();
                      return Promise.ofException(new RuntimeException("Auth failure.", e));
                    }));
}
```
(note `connection.close()` call in `connectAuth()` method)
Then replace all the occurrences of `client.connect()` with `connectAuth(client)` (inside [RedisConnectionTestWithReal](https://github.com/activej/activej/blob/master/extra/cloud-redis/src/test/java/io/activej/redis/RedisConnectionTestWithReal.java) class). We have tested ACL authentication with this setup and all of the tests have passed. Please, give it a try and let us know if you still have any issues.
 
As for whether or not you should use connection pooling is up to you and depends on your workload, performance requirements. Usually, it is a good practice to use connection pooling as the creation of a new TCP connection takes some time/resources. Plus, you could call AUTH command only for a newly created connection, thus saving some time.

**Comment by a1730** [comment]
Hello @eduard-vasinskyi ,

Yes, we are having a ball using ActiveJ and, equally important, learning from the code base.
We implemented your suggestion with  RedisConnectionTestWithReal  and all packaged tests passed - naturally.
Also, our ActiveJ Redis clients are connecting successfully to with Redis Cloud where ACL is enabled. We are even using them as RedisJSON  clients. The cmd interface is very flexible and empowering.

This leads me to plead for an enhancement - a **RedisClient#connect(username,password)** method. 

I believe a method like that would have prevented this issue. Should I open a separate issue for the enhancement request?
We tried to make the changes locally but RedisClient and RedisConnection are final classes so we hope the request will be granted.

We are not using connection pooling at this time.

I'll leave the issue open for now to help others who need to deal with Redis ACL.
Thank you for your support.

**Comment by eduard-vasinskyi** [comment]
@a1730, thank you for the suggestion!
 
We will add both `RedisClient#connect(password)` (for simple authentication without ACL) and `RedisClient#connect(username,password)` methods. We also plan to introduce `RedisAuthenticationException` to indicate that the server requires authentication or that credentials are invalid. This will be part of the ActiveJ v4.2 release.
 
Please leave this issue open, I will post updates here.

**Comment by a1730** [comment]
Hi @eduard-vasinskyi ,
I noticed that dev is almost complete on the connect enhancement. Thank you.
May I suggest that connect please return Redis response when there are connection issues rather than swallowing [connect](https://github.com/activej/activej/blob/b47b4ef4e2db6e25bd911014a00126f629e5862a/extra/cloud-redis/src/main/java/io/activej/redis/RedisClient.java#L183) error ? https://github.com/activej/activej/blob/b47b4ef4e2db6e25bd911014a00126f629e5862a/extra/cloud-redis/src/main/java/io/activej/redis/RedisClient.java#L183
DevOps will thank you for visibility to why Redis '_suddenly_' stopped working.

Thank you very much.
I appreciate you.

**Comment by eduard-vasinskyi** [comment]
The connection error is actually not swallowed here. The code in `RedisConnection#connectAndAuth` looks like this:
```
return connect()
   	  .then(connection -> ...)
```
 
`.then(...)` would be executed only if `connect()` returns successfully. Otherwise, the exception would be propagated further down the promise chain.
You can take a look at [docs for chaining promises](https://activej.io/promise.html#chaining-promises) or documentation of [Promise chain methods](https://github.com/activej/activej/blob/master/core-promise/src/main/java/io/activej/promise/Promise.java).
If the server is unresponsive, the whole `connect(username, password)` will be completed exceptionally with the initial `java.net.ConnectException` as a cause.
You can ensure it by trying to connect to a non-existing Redis server:
```
Eventloop eventloop = Eventloop.create().withCurrentThread();
RedisClient client = RedisClient.create(eventloop, new InetSocketAddress(1234));
client.connect("user", "pass")
     .whenResult(connection -> System.out.println("New connection! " + connection))
     .whenException(e -> System.err.println("Failed to connect: " + e + ", cause: " + e.getCause()));
eventloop.run();
```
It would print: 
*Failed to connect: io.activej.redis.RedisException: Failed to connect to Redis server: 0.0.0.0/0.0.0.0:1234, cause: java.net.ConnectException: Connection refused: no further information*
`.whenResult(...)` handler would not be called.

**Comment by a1730** [comment]
Sorry I misspoke.  I should be more careful in the future.
What I meant was that we should not eat the authentication result from Redis. but I was thinking of the scenario from the point of view of someone using the connect method, hence the mistake.
You are right that connectivity issue:
```Could not connect to Redis at 127.0.0.1:6379: Connection refused
not connected>
is properly handled.
```
I was referring in the case there is a valid network connectivity to Redis but authentication failed.
```~> redis-cli
Warning: AUTH failed
redisdb:10458> get a
(error) NOAUTH Authentication required
```
It is not essential, but definitely would be nice, to see those messages from Redis.
Apologies for my earlier lack of precision.

**Comment by a1730** [comment]
You are right.
I got the message by re-running the test after a Gradle clean.
Thank you.
Please feel free to close the issue at your convenience.

**Comment by eduard-vasinskyi** [comment]
Hello, @a1730
ActiveJ v4.2 has been released! It contains new `connect()` methods with authentication as well as new specialized authentication/permission exceptions.

**Comment by a1730** [comment]
Hello @eduard-vasinskyi,
Congratulations on the release of v4.2.
We appreciate your efforts getting enhanced Redis ACL support into a released version of ActiveJ.
We cannot thank you enough for the excellent support we received during our testing of the feature.
Be careful, no good deed shall go unpunished! We will be talking about ActiveJ, the people and the product of course, to anyone who will listen. We are rooting for you.
THANK YOU.
