### ISSUE TITLE
ApplicationSettings [question]

### ISSUE THREAD

**Issue by a1730** [activej/activej#74]
ApplicationSettings looks pretty nifty. How does one configure, and use this beast?
We looked at Config but Config does not have the converters provided by ApplicationSettings.
Any pointers/examples will be appreciated.
Thank you.

**Comment by eduard-vasinskyi** [comment]
Hello, @a1730
[ApplicationSettings](https://github.com/activej/activej/blob/master/util-common/src/main/java/io/activej/common/ApplicationSettings.java) class is used for initializing runtime constant values. There are times when you do not want to / cannot change the code but need to change the behavior of an application. This can be used for debugging, tuning performance, enabling/disabling monitoring, etc. 

Using `ApplicationSettings` for static constants is similar to using Java asserts. It allows JIT to perform runtime constant optimizations, dead code elimination, leading to zero-overhead.

To initialize a constant value using `ApplicationSettings` you need to pass the enclosing class, the name of the value to be initialized, and a default value of a constant.

Let’s take a look at `ByteBufPool#STATS` constant: https://github.com/activej/activej/blob/2d8c97284f3af5f033c6e21ecbe96a1c4677f68e/core-bytebuf/src/main/java/io/activej/bytebuf/ByteBufPool.java#L77
This constant determines whether or not additional statistics for ByteBufPool should be collected. By default, it is set to `false`. To enable it, we can start the application with system property: `-DByteBufPool.stats=true`
If there are possible class/constant name collisions, you can also use full class name: `-Dio.activej.bytebuf.ByteBufPool.stats=true`

By default, the `ApplicationSettings` class uses system properties to look up which constant should be overwritten. But you can pass some other properties by calling `ApplicationSettings#useProperties`. Or you can set up custom application settings in your code using the `ApplicationSettings#set` method. Note that `useProperties` and `set` method should be executed prior to the initialization of a class that contains constant values to overwrite.

Although, [Config](https://github.com/activej/activej/blob/master/boot-config/src/main/java/io/activej/config/Config.java) may seem a bit similar to `ApplicationSettings`, the difference is that Config is used to initialize instance variables while ApplicationSettings allows initializing constant values.

**Comment by a1730** [comment]
Hello @eduard-vasinskyi ,

Beautiful. We have already started using ApplicationSettings. We bootstrap ApplicationSettngs with an EffectiveConfig of our application constants.
Thank you for the explanation.
