### ISSUE TITLE
Maven repository missing jar file

### ISSUE THREAD

**Issue by Wdestroier** [activej/activej#76]
Hi, for some reason the artifact is missing! :(

How to reproduce the behavior:

Access the link https://repo1.maven.org/maven2/io/activej/activej/4.2/ and see that there's no jar file.

Expected behavior:

Have a jar file as in https://repo1.maven.org/maven2/com/google/guava/guava/30.1.1-jre/

**Comment by eduard-vasinskyi** [comment]
Hello, @Wdestroier
There are no .jar artifacts for `io.activej.activej`
It is a parent pom configuration for all of the other ActiveJ modules. You can add ActveJ dependencies by specifying the artifact ID of a concrete module that you need. (e.g.  `activej-http`, `activej-fs`, etc)

You can ensure that there are .jar files for ActiveJ modules here, for example:
https://repo1.maven.org/maven2/io/activej/activej-http/4.2/
https://repo1.maven.org/maven2/io/activej/activej-fs/4.2/

**Comment by Wdestroier** [comment]
Ohhh, I got it now.

Thanks @eduard-vasinskyi :)
