### ISSUE TITLE
Incorrect Links in Documentation

### ISSUE THREAD

**Issue by sirinath** [activej/activej#8]
In numerous places, in the documentation, there are incorrectly linked links. E.g.:
- ![image](https://user-images.githubusercontent.com/637415/86211874-aa017e80-bb94-11ea-89f0-7d482616d3e2.png) in https://fs.activej.io/
- ![image](https://user-images.githubusercontent.com/637415/86212754-437d6000-bb96-11ea-9c83-44fc02818da3.png) in https://rpc.activej.io/
- etc.

**Comment by valerialistratova** [comment]
@sirinath thank you for the feedback! The links you've mentioned in the issue were fixed. We'll additionally search through the docs to find any other broken links.

**Comment by sirinath** [comment]
Router Module Example full example points to https://github.com/activej/activej/blob/master/examples/core/http/src/main/java/ScopeServletExample.java
