### ISSUE TITLE
Could I use a mybatis?

### ISSUE THREAD

**Issue by HeeJoon-Kim** [activej/activej#80]
Could I use a mybatis?

Hi. I'm a newbie in java and spring. I used a activj's sql example, but i dislike a query string in java source.

So, i would like to use a mybatis with a @mapper annotation, interface class and query xml.

How can do it? When use a like that, a performance will decrese?

**Comment by eduard-vasinskyi** [comment]
Hello, @HeeJoon-Kim

Yes, you can use mybatis with ActiveJ. As well as any other ORM or SQL builder library, like JOOQ. The approach is similar to the one described in the SQL example. Just wrap your blocking code inside `Promise.ofBlockingCallable()` / `Promise.ofBlockingRunnable()` and pass an executor that would run blocking code:
```
Promise.ofBlockingRunnable(executor,
     () -> {
       try (SqlSession session = sqlSessionFactory.openSession()) {
        Student student = new Student("Jack", "London", "jacklondon@example.com");
        session.insert("Student.insert", student);
        session.commit();
       }
     });
 ```
In fact, you can use this approach anytime you need to call blocking code from inside `Eventloop`.

Given code has almost no performance overhead by itself. The bottleneck here would be the DB driver, executor/thread pool, and the database.

**Comment by HeeJoon-Kim** [comment]
Thank you for ur reply. I will try it.
