### ISSUE TITLE
Can you provide documentation on the implementation principle or architecture? 

### ISSUE THREAD

**Issue by test210820** [activej/activej#81]
Can provide documentation on the implementation principle or architecture?  I am very interested it

**Comment by eduard-vasinskyi** [comment]
Hello, @zxf-thingsmatrix
What do you mean by the implementation principle? 
You can take a look at the https://activej.io/ website for the documentation/tutorials. This is a good starting point to get involved with ActiveJ. 
ActiveJ threading model is described [here](https://activej.io/workers.html)
There are also various [examples](https://github.com/activej/activej/tree/master/examples) for each ActiveJ module that you can use as a reference when using ActiveJ in your application
