### ISSUE TITLE
How to add SNI names to AsyncHttpClient

### ISSUE THREAD

**Issue by Kilobyte1000** [activej/activej#85]
How can SNI names be added on an AsyncHttpClient? As per my understanding from these [oracle docs](https://docs.oracle.com/en/java/javase/14/security/java-secure-socket-extension-jsse-reference-guide.html#GUID-82B884DF-AA3D-4FE1-8991-9C3F14044C4F), access to the SSLEngine is needed to add SNI names to the protocol, but the api does not provide a way to access the engine

**Comment by eduard-vasinskyi** [comment]
Hello, @Kilobyte1000
We plan to add SNI support for both HTTP client and server in future releases of ActiveJ.
Thank you for the suggestion!
