### ISSUE TITLE
Failed test when running mvn clean install

### ISSUE THREAD

**Issue by Danilo3** [activej/activej#89]
Following tests are failed: 
[ERROR] Failures:
[ERROR]   ValueStatsTest.itShouldProperlyBuildStringForNegativeNumbers:411->assertNumberOfDigitsAfterDot:763 expected:<-0[,]99> but was:<-0[.]99>
[ERROR]   ValueStatsTest.itShouldProperlyBuildStringForPositiveNumbers:369->assertNumberOfDigitsAfterDot:763 expected:<9989[,]24> but was:<9989[.]24>

OS: Windows 10 20H2
Java: 16.0.1
![screenshot](https://user-images.githubusercontent.com/18246017/120112993-19a33380-c181-11eb-8ed7-493127315338.png)

**Comment by eduard-vasinskyi** [comment]
Thank you for spotting that, @Danilo3!
We have fixed tests in the `master` branch. The fix will be part of the next ActiveJ release. For now, you can install ActiveJ locally either with -DskipTests maven option or by calling ‘./install.sh’ from the root of the repository.
