### ISSUE TITLE
Integrate Website and Blog to Utterances

### ISSUE THREAD

**Issue by sirinath** [activej/activej#9]
Can you integrate your website and blog into [Utterances](https://utteranc.es/) so anybody can comment on every page and also any issues are on GitHub if they are actionable.

Also, it would be good to have the blog on GitHub also with an edit in GitHub link so the community can contribute to making small corrections. Also, integrate with [Utterances](https://utteranc.es/) for comments and issues.

**Comment by valerialistratova** [comment]
@sirinath thank you for the suggestions, we'll consider applying them in the future
