### ISSUE TITLE
using activej-codegen,  how to call super method

### ISSUE THREAD

**Issue by zhangtianxiao** [activej/activej#94]
current class has same method name as parent class
I want call the method  of the parent class
does active-codegen have expression like  `supercall`
thanks

**Comment by eduard-vasinskyi** [comment]
Hello, @zhangtianxiao
Thank you for the suggestion! We have added [Expressions#callSuper](https://github.com/activej/activej/blob/b5d914ccd30782ca6ea8ebdd96ebe8f91e647735/core-codegen/src/main/java/io/activej/codegen/expression/Expressions.java#L515) method in the master branch. It is quite straightforward, but you can look at the test in [ExpressionTest](https://github.com/activej/activej/blob/b5d914ccd30782ca6ea8ebdd96ebe8f91e647735/core-codegen/src/test/java/io/activej/codegen/expression/ExpressionTest.java#L1024) for a reference.
`Expressions#callSuper` will be part of the ActiveJ v4.4 release.
