### ISSUE TITLE
Benchmark from the-benchmarker is missing

### ISSUE THREAD

**Issue by Wdestroier** [activej/activej#96]
Hi, I noticed that ActiveJ was not the top 1 of the list anymore.

I didn't notice it until today, but it disappeared from the list!

I'm not sure what happened, if it's not compiling or smth.

Desired behavior: it should show in the list that can be found at:
https://web-frameworks-benchmark.netlify.app/result
https://github.com/the-benchmarker/web-frameworks

**Comment by eduard-vasinskyi** [comment]
Hello, @Wdestroier 
It seems like after the recent run, some frameworks are missing from the test result web page. Looks like it will be fixed soon. 
See:  https://github.com/the-benchmarker/web-frameworks/issues/4405#issuecomment-862388548

**Comment by Wdestroier** [comment]
Thanks, @eduard-vasinskyi 😄
